import type { DomainData } from "./types";

export const domainData: DomainData = {
  territories: [
    { id: "territory-joal", name: "Joal-Fadiouth", region: "Thiès", status: "active" },
    { id: "territory-kayar", name: "Kayar", region: "Thiès", status: "active" },
  ],
  organizations: [
    { id: "org-piroguiers-joal", name: "Union des piroguiers de Joal", organizationType: "fisher_organization", territoryId: "territory-joal", status: "active" },
    { id: "org-quai-joal", name: "Gestion du quai central de Joal", organizationType: "landing_site_management", territoryId: "territory-joal", status: "active" },
    { id: "org-mareyeurs-thies", name: "Mareyeurs Thiès Littoral", organizationType: "buyer", territoryId: "territory-joal", status: "active" },
    { id: "org-froid-saloum", name: "Froid Saloum Services", organizationType: "cold_chain_provider", territoryId: "territory-joal", status: "active" },
    { id: "org-quai-kayar", name: "Gestion du quai de Kayar", organizationType: "landing_site_management", territoryId: "territory-kayar", status: "active" },
  ],
  actors: [
    { id: "actor-mamadou", name: "Mamadou Ndiaye", actorType: "captain", organizationId: "org-piroguiers-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-ibrahima", name: "Ibrahima Fall", actorType: "fisher", organizationId: "org-piroguiers-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-awa", name: "Awa Diouf", actorType: "landing_site_agent", organizationId: "org-quai-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-babacar", name: "Babacar Sarr", actorType: "weigher", organizationId: "org-quai-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-fatou", name: "Fatou Seck", actorType: "buyer", organizationId: "org-mareyeurs-thies", territoryId: "territory-joal", status: "active" },
    { id: "actor-khadija", name: "Khadija Ba", actorType: "processor", organizationId: "org-mareyeurs-thies", territoryId: "territory-joal", status: "active" },
    { id: "actor-cheikh", name: "Cheikh Gueye", actorType: "cold_chain_operator", organizationId: "org-froid-saloum", territoryId: "territory-joal", status: "active" },
    { id: "actor-omar", name: "Omar Sy", actorType: "transporter", organizationId: "org-mareyeurs-thies", territoryId: "territory-joal", status: "active" },
    { id: "actor-aminata", name: "Aminata Cissé", actorType: "territorial_coordinator", organizationId: "org-quai-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-moussa", name: "Moussa Kane", actorType: "captain", organizationId: "org-piroguiers-joal", territoryId: "territory-kayar", status: "active" },
    { id: "actor-sokhna", name: "Sokhna Mbaye", actorType: "landing_site_agent", organizationId: "org-quai-kayar", territoryId: "territory-kayar", status: "active" },
    { id: "actor-directeur", name: "Direction des pêches artisanales", actorType: "institutional_decision_maker", territoryId: "territory-joal", status: "active" },
  ],
  landingSites: [
    { id: "site-joal-central", name: "Quai central de Joal", territoryId: "territory-joal", managerOrganizationId: "org-quai-joal", capacities: {}, operationalStatus: "constrained" },
    { id: "site-joal-secondaire", name: "Site secondaire de Joal", territoryId: "territory-joal", managerOrganizationId: "org-quai-joal", capacities: {}, operationalStatus: "operational" },
    { id: "site-kayar-central", name: "Quai central de Kayar", territoryId: "territory-kayar", managerOrganizationId: "org-quai-kayar", capacities: {}, operationalStatus: "operational" },
  ],
  vessels: [
    { id: "vessel-jambar", name: "Jambar", registrationNumber: "SN-JOA-001", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "operational" },
    { id: "vessel-teranga", name: "Teranga", registrationNumber: "SN-JOA-002", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "operational" },
    { id: "vessel-linguere", name: "Linguère", registrationNumber: "SN-JOA-003", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-secondaire", status: "operational" },
    { id: "vessel-ndanaan", name: "Ndaanaan", registrationNumber: "SN-JOA-004", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "maintenance" },
    { id: "vessel-kayar-1", name: "Kayar 1", registrationNumber: "SN-KAY-001", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-kayar-central", status: "operational" },
    { id: "vessel-kayar-2", name: "Kayar 2", registrationNumber: "SN-KAY-002", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-kayar-central", status: "operational" },
    { id: "vessel-sunu-galie", name: "Sunu Gaal", registrationNumber: "SN-JOA-005", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "operational" },
    { id: "vessel-baobab", name: "Baobab", registrationNumber: "SN-JOA-006", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-secondaire", status: "operational" },
  ],
  expectedReturns: [
    { id: "return-001", vesselId: "vessel-jambar", expectedLandingSiteId: "site-joal-central", expectedAt: "2026-07-25T08:30:00Z", estimatedCatch: [{ species: "Sardinelle", estimatedWeightKg: 1800 }], status: "arrived", createdByActorId: "actor-mamadou", createdAt: "2026-07-25T05:15:00Z" },
    { id: "return-002", vesselId: "vessel-teranga", expectedLandingSiteId: "site-joal-central", expectedAt: "2026-07-25T09:10:00Z", estimatedCatch: [{ species: "Thiof", estimatedWeightKg: 700 }, { species: "Dorade", estimatedWeightKg: 350 }], status: "arrived", createdByActorId: "actor-mamadou", createdAt: "2026-07-25T05:40:00Z" },
    { id: "return-003", vesselId: "vessel-linguere", expectedLandingSiteId: "site-joal-secondaire", expectedAt: "2026-07-25T10:20:00Z", estimatedCatch: [{ species: "Sardinelle", estimatedWeightKg: 1200 }], status: "approaching", createdByActorId: "actor-ibrahima", createdAt: "2026-07-25T06:10:00Z" },
    { id: "return-004", vesselId: "vessel-sunu-galie", expectedLandingSiteId: "site-joal-central", expectedAt: "2026-07-25T11:00:00Z", estimatedCatch: [{ species: "Maquereau", estimatedWeightKg: 1500 }], status: "announced", createdByActorId: "actor-mamadou", createdAt: "2026-07-25T06:25:00Z" },
    { id: "return-005", vesselId: "vessel-kayar-1", expectedLandingSiteId: "site-kayar-central", expectedAt: "2026-07-25T09:40:00Z", estimatedCatch: [{ species: "Sardinelle", estimatedWeightKg: 1400 }], status: "arrived", createdByActorId: "actor-moussa", createdAt: "2026-07-25T05:50:00Z" },
    { id: "return-006", vesselId: "vessel-kayar-2", expectedLandingSiteId: "site-kayar-central", expectedAt: "2026-07-25T12:00:00Z", estimatedCatch: [{ species: "Thon", estimatedWeightKg: 900 }], status: "announced", createdByActorId: "actor-moussa", createdAt: "2026-07-25T06:45:00Z" },
  ],
  serviceNeeds: [
    { id: "service-need-001", expectedReturnId: "return-001", requestedByActorId: "actor-mamadou", needType: "ice", requestedQuantity: 1200, unit: "kg", neededAt: "2026-07-25T08:20:00Z", territoryId: "territory-joal", landingSiteId: "site-joal-central", priority: "urgent", status: "fulfilled", note: "Glace nécessaire avant la pesée.", createdAt: "2026-07-25T05:16:00Z" },
    { id: "service-need-002", expectedReturnId: "return-001", requestedByActorId: "actor-mamadou", needType: "transport", requestedQuantity: 1, unit: "vehicle", neededAt: "2026-07-25T09:00:00Z", territoryId: "territory-joal", landingSiteId: "site-joal-central", priority: "normal", status: "allocated", createdAt: "2026-07-25T05:17:00Z" },
    { id: "service-need-003", expectedReturnId: "return-002", requestedByActorId: "actor-mamadou", needType: "cold_storage", requestedQuantity: 700, unit: "kg", neededAt: "2026-07-25T09:15:00Z", territoryId: "territory-joal", landingSiteId: "site-joal-central", priority: "urgent", status: "partially_allocated", createdAt: "2026-07-25T05:42:00Z" },
    { id: "service-need-004", expectedReturnId: "return-003", requestedByActorId: "actor-ibrahima", needType: "ice", requestedQuantity: 700, unit: "kg", neededAt: "2026-07-25T10:10:00Z", territoryId: "territory-joal", landingSiteId: "site-joal-secondaire", priority: "normal", status: "open", createdAt: "2026-07-25T06:12:00Z" },
    { id: "service-need-005", expectedReturnId: "return-004", requestedByActorId: "actor-mamadou", needType: "transport", requestedQuantity: 2, unit: "vehicle", neededAt: "2026-07-25T11:15:00Z", territoryId: "territory-joal", landingSiteId: "site-joal-central", priority: "critical", status: "partially_allocated", createdAt: "2026-07-25T06:27:00Z" },
    { id: "service-need-006", expectedReturnId: "return-005", requestedByActorId: "actor-moussa", needType: "ice", requestedQuantity: 900, unit: "kg", neededAt: "2026-07-25T09:30:00Z", territoryId: "territory-kayar", landingSiteId: "site-kayar-central", priority: "urgent", status: "fulfilled", createdAt: "2026-07-25T05:52:00Z" },
    { id: "service-need-007", expectedReturnId: "return-006", requestedByActorId: "actor-moussa", needType: "cold_storage", requestedQuantity: 800, unit: "kg", neededAt: "2026-07-25T12:00:00Z", territoryId: "territory-kayar", landingSiteId: "site-kayar-central", priority: "urgent", status: "open", createdAt: "2026-07-25T06:47:00Z" },
  ],
  serviceAllocations: [
    { id: "allocation-001", serviceNeedId: "service-need-001", capacityId: "capacity-002", allocatedQuantity: 1200, unit: "kg", providerOrganizationId: "org-froid-saloum", beneficiaryOrganizationId: "org-piroguiers-joal", beneficiaryActorId: "actor-mamadou", allocatedByActorId: "actor-aminata", allocatedAt: "2026-07-25T06:00:00Z", status: "fulfilled" },
    { id: "allocation-002", serviceNeedId: "service-need-002", capacityId: "capacity-003", allocatedQuantity: 1, unit: "vehicle", providerOrganizationId: "org-mareyeurs-thies", beneficiaryOrganizationId: "org-piroguiers-joal", beneficiaryActorId: "actor-mamadou", allocatedByActorId: "actor-aminata", allocatedAt: "2026-07-25T06:05:00Z", status: "reserved" },
    { id: "allocation-003", serviceNeedId: "service-need-003", capacityId: "capacity-001", allocatedQuantity: 500, unit: "kg", providerOrganizationId: "org-froid-saloum", beneficiaryOrganizationId: "org-piroguiers-joal", beneficiaryActorId: "actor-mamadou", allocatedByActorId: "actor-aminata", allocatedAt: "2026-07-25T07:30:00Z", status: "reserved" },
    { id: "allocation-004", serviceNeedId: "service-need-005", capacityId: "capacity-003", allocatedQuantity: 1, unit: "vehicle", providerOrganizationId: "org-mareyeurs-thies", beneficiaryOrganizationId: "org-piroguiers-joal", beneficiaryActorId: "actor-mamadou", allocatedByActorId: "actor-aminata", allocatedAt: "2026-07-25T08:00:00Z", status: "reserved" },
    { id: "allocation-005", serviceNeedId: "service-need-006", capacityId: "capacity-005", allocatedQuantity: 900, unit: "kg", providerOrganizationId: "org-quai-kayar", beneficiaryOrganizationId: "org-piroguiers-joal", beneficiaryActorId: "actor-moussa", allocatedByActorId: "actor-sokhna", allocatedAt: "2026-07-25T06:20:00Z", status: "fulfilled" },
  ],
  serviceExecutions: [
    { id: "execution-001", allocationId: "allocation-001", executedQuantity: 1200, executedAt: "2026-07-25T08:10:00Z", confirmedByActorId: "actor-cheikh", evidence: [{ label: "Bon de livraison glace", reference: "BL-GLACE-001", confidenceLevel: "verified" }], status: "confirmed" },
    { id: "execution-002", allocationId: "allocation-005", executedQuantity: 900, executedAt: "2026-07-25T09:20:00Z", confirmedByActorId: "actor-sokhna", evidence: [{ label: "Confirmation du gestionnaire du quai", reference: "KAYAR-GLACE-005", confidenceLevel: "confirmed" }], status: "confirmed" },
  ],
  landings: [
    { id: "landing-001", expectedReturnId: "return-001", vesselId: "vessel-jambar", landingSiteId: "site-joal-central", landedAt: "2026-07-25T08:26:00Z", status: "confirmed", confirmedByActorId: "actor-awa" },
    { id: "landing-002", expectedReturnId: "return-002", vesselId: "vessel-teranga", landingSiteId: "site-joal-central", landedAt: "2026-07-25T09:03:00Z", status: "confirmed", confirmedByActorId: "actor-awa" },
    { id: "landing-003", expectedReturnId: "return-005", vesselId: "vessel-kayar-1", landingSiteId: "site-kayar-central", landedAt: "2026-07-25T09:37:00Z", status: "confirmed", confirmedByActorId: "actor-sokhna" },
    { id: "landing-004", vesselId: "vessel-baobab", landingSiteId: "site-joal-secondaire", landedAt: "2026-07-25T07:50:00Z", status: "confirmed", confirmedByActorId: "actor-awa" },
  ],
  weighings: [
    { id: "weighing-001", landingId: "landing-001", measuredAt: "2026-07-25T08:42:00Z", totalWeightKg: 1720, method: "digital_scale", confidenceLevel: "verified", verifiedByActorId: "actor-babacar" },
    { id: "weighing-002", landingId: "landing-002", measuredAt: "2026-07-25T09:20:00Z", totalWeightKg: 1010, method: "digital_scale", confidenceLevel: "verified", verifiedByActorId: "actor-babacar" },
    { id: "weighing-003", landingId: "landing-003", measuredAt: "2026-07-25T09:55:00Z", totalWeightKg: 1340, method: "mechanical_scale", confidenceLevel: "confirmed", verifiedByActorId: "actor-sokhna" },
    { id: "weighing-004", landingId: "landing-004", measuredAt: "2026-07-25T08:05:00Z", totalWeightKg: 620, method: "digital_scale", confidenceLevel: "verified", verifiedByActorId: "actor-babacar" },
  ],
  lots: [
    { id: "lot-001", landingId: "landing-001", species: "Sardinelle", weightKg: 900, qualityGrade: "standard", conservationStatus: "iced", availabilityStatus: "partially_reserved", askingPricePerKg: 650, currency: "XOF" },
    { id: "lot-002", landingId: "landing-001", species: "Sardinelle", weightKg: 520, qualityGrade: "processing", conservationStatus: "fresh", availabilityStatus: "available", askingPricePerKg: 500, currency: "XOF" },
    { id: "lot-003", landingId: "landing-001", species: "Sardinelle", weightKg: 300, qualityGrade: "standard", conservationStatus: "at_risk", availabilityStatus: "available", askingPricePerKg: 450, currency: "XOF" },
    { id: "lot-004", landingId: "landing-002", species: "Thiof", weightKg: 620, qualityGrade: "premium", conservationStatus: "chilled", availabilityStatus: "reserved", askingPricePerKg: 3200, currency: "XOF" },
    { id: "lot-005", landingId: "landing-002", species: "Dorade", weightKg: 390, qualityGrade: "premium", conservationStatus: "fresh", availabilityStatus: "available", askingPricePerKg: 2800, currency: "XOF" },
    { id: "lot-006", landingId: "landing-003", species: "Sardinelle", weightKg: 800, qualityGrade: "standard", conservationStatus: "iced", availabilityStatus: "available", askingPricePerKg: 600, currency: "XOF" },
    { id: "lot-007", landingId: "landing-003", species: "Sardinelle", weightKg: 540, qualityGrade: "processing", conservationStatus: "fresh", availabilityStatus: "available", askingPricePerKg: 480, currency: "XOF" },
    { id: "lot-008", landingId: "landing-004", species: "Maquereau", weightKg: 280, qualityGrade: "standard", conservationStatus: "fresh", availabilityStatus: "sold", askingPricePerKg: 900, currency: "XOF" },
    { id: "lot-009", landingId: "landing-004", species: "Sardinelle", weightKg: 220, qualityGrade: "processing", conservationStatus: "at_risk", availabilityStatus: "available", askingPricePerKg: 500, currency: "XOF" },
  ],
  marketNeeds: [
    { id: "need-001", actorId: "actor-fatou", organizationId: "org-mareyeurs-thies", species: "Sardinelle", quantityKg: 1000, territoryId: "territory-joal", neededBy: "2026-07-25T13:00:00Z", status: "partially_matched", relatedLotIds: ["lot-001"] },
    { id: "need-002", actorId: "actor-khadija", organizationId: "org-mareyeurs-thies", species: "Sardinelle", quantityKg: 600, territoryId: "territory-joal", neededBy: "2026-07-25T14:30:00Z", status: "open", relatedLotIds: ["lot-002", "lot-003"] },
    { id: "need-003", actorId: "actor-fatou", organizationId: "org-mareyeurs-thies", species: "Dorade", quantityKg: 300, territoryId: "territory-joal", neededBy: "2026-07-25T12:30:00Z", status: "matched", relatedLotIds: ["lot-005"] },
    { id: "need-004", actorId: "actor-khadija", organizationId: "org-mareyeurs-thies", species: "Sardinelle", quantityKg: 500, territoryId: "territory-kayar", neededBy: "2026-07-25T15:00:00Z", status: "open", relatedLotIds: ["lot-006"] },
  ],
  capacities: [
    { id: "capacity-001", providerOrganizationId: "org-froid-saloum", capacityType: "cold_storage", territoryId: "territory-joal", landingSiteId: "site-joal-central", initialQuantity: 1800, availableQuantity: 1300, unit: "kg", availableFrom: "2026-07-25T09:00:00Z", availableUntil: "2026-07-25T18:00:00Z", declaredByActorId: "actor-cheikh", createdAt: "2026-07-25T05:00:00Z", status: "partially_available" },
    { id: "capacity-002", providerOrganizationId: "org-froid-saloum", capacityType: "ice", territoryId: "territory-joal", landingSiteId: "site-joal-central", initialQuantity: 2200, availableQuantity: 1000, unit: "kg", availableFrom: "2026-07-25T06:00:00Z", availableUntil: "2026-07-25T12:00:00Z", declaredByActorId: "actor-cheikh", createdAt: "2026-07-25T04:50:00Z", status: "partially_available" },
    { id: "capacity-003", providerOrganizationId: "org-mareyeurs-thies", capacityType: "transport", territoryId: "territory-joal", landingSiteId: "site-joal-central", initialQuantity: 2, availableQuantity: 0, unit: "vehicle", availableFrom: "2026-07-25T08:30:00Z", availableUntil: "2026-07-25T14:00:00Z", declaredByActorId: "actor-omar", createdAt: "2026-07-25T05:10:00Z", status: "allocated" },
    { id: "capacity-004", providerOrganizationId: "org-mareyeurs-thies", capacityType: "processing", territoryId: "territory-joal", landingSiteId: "site-joal-secondaire", initialQuantity: 8, availableQuantity: 8, unit: "slot", availableFrom: "2026-07-25T12:00:00Z", availableUntil: "2026-07-25T18:00:00Z", declaredByActorId: "actor-khadija", createdAt: "2026-07-25T06:00:00Z", status: "available" },
    { id: "capacity-005", providerOrganizationId: "org-quai-kayar", capacityType: "ice", territoryId: "territory-kayar", landingSiteId: "site-kayar-central", initialQuantity: 1000, availableQuantity: 100, unit: "kg", availableFrom: "2026-07-25T06:00:00Z", availableUntil: "2026-07-25T12:00:00Z", declaredByActorId: "actor-sokhna", createdAt: "2026-07-25T05:00:00Z", status: "partially_available" },
  ],
  tensions: [
    { id: "tension-001", tensionType: "cold_storage_shortage", severity: "high", territoryId: "territory-joal", relatedEntityType: "service_need", relatedEntityId: "service-need-003", description: "200 kg de besoin froid restent non couverts pour le retour Teranga.", status: "coordinating", reportedByActorId: "actor-awa", reportedAt: "2026-07-25T07:35:00Z" },
    { id: "tension-002", tensionType: "transport_shortage", severity: "high", territoryId: "territory-joal", relatedEntityType: "service_need", relatedEntityId: "service-need-005", description: "Un véhicule supplémentaire est nécessaire pour le retour Sunu Gaal.", status: "open", reportedByActorId: "actor-aminata", reportedAt: "2026-07-25T08:05:00Z" },
    { id: "tension-003", tensionType: "landing_site_saturation", severity: "medium", territoryId: "territory-kayar", relatedEntityType: "expected_return", relatedEntityId: "return-006", description: "Risque de chevauchement de deux retours avec capacité de manutention limitée.", status: "resolved", reportedByActorId: "actor-sokhna", reportedAt: "2026-07-25T08:55:00Z" },
  ],
  commitments: [
    { id: "commitment-001", tensionId: "tension-001", organizationId: "org-froid-saloum", action: "Identifier 200 kg de capacité froide supplémentaire.", dueAt: "2026-07-25T09:45:00Z", status: "accepted" },
    { id: "commitment-002", tensionId: "tension-001", actorId: "actor-omar", action: "Préparer une réorientation vers le site secondaire si aucune capacité n'est trouvée.", dueAt: "2026-07-25T10:00:00Z", status: "in_progress" },
    { id: "commitment-003", tensionId: "tension-002", actorId: "actor-omar", action: "Mobiliser un second véhicule léger.", dueAt: "2026-07-25T10:30:00Z", status: "proposed" },
    { id: "commitment-004", tensionId: "tension-003", actorId: "actor-sokhna", action: "Décaler l'arrivée de Kayar 2 de vingt minutes.", dueAt: "2026-07-25T11:40:00Z", status: "completed", completedAt: "2026-07-25T09:20:00Z" },
  ],
  outcomes: [
    { id: "outcome-001", relatedEntityType: "tension", relatedEntityId: "tension-003", outcomeType: "service_continuity_restored", description: "Le décalage du second retour a évité la saturation du quai de Kayar.", valueSavedKg: 900, recordedAt: "2026-07-25T09:25:00Z", evidence: [{ label: "Confirmation du gestionnaire du quai", reference: "commitment-004", confidenceLevel: "confirmed" }] },
    { id: "outcome-002", relatedEntityType: "service_execution", relatedEntityId: "execution-001", outcomeType: "loss_avoided", description: "La livraison de glace a protégé 1 200 kg de sardinelle avant débarquement.", valueSavedKg: 1200, valueCreated: 180000, currency: "XOF", recordedAt: "2026-07-25T08:15:00Z", evidence: [{ label: "Bon de livraison glace", reference: "BL-GLACE-001", confidenceLevel: "verified" }] },
    { id: "outcome-003", relatedEntityType: "market_need", relatedEntityId: "need-003", outcomeType: "market_matched", description: "Le besoin de dorade a été couvert par le lot 005.", valueCreated: 840000, currency: "XOF", recordedAt: "2026-07-25T10:05:00Z", evidence: [{ label: "Lot réservé et besoin clôturé", reference: "lot-005", confidenceLevel: "verified" }] },
  ],
};