import type { DomainData } from "./types";

export const domainData: DomainData = {
  territories: [
    { id: "territory-joal", name: "Joal-Fadiouth", region: "Thiès", status: "active" },
    { id: "territory-kayar", name: "Kayar", region: "Thiès", status: "active" },
  ],
  organizations: [
    { id: "org-piroguiers-joal", name: "Union des piroguiers de Joal", organizationType: "fisher_organization", territoryId: "territory-joal", status: "active" },
    { id: "org-quai-joal", name: "Gestion du quai central de Joal", organizationType: "landing_site_management", territoryId: "territory-joal", status: "active" },
    { id: "org-mareyeurs-thies", name: "Mareyeurs Thiès Littoral", organizationType: "buyer", territoryId: "territory-joal", status: "active" },
    { id: "org-froid-saloum", name: "Froid Saloum Services", organizationType: "cold_chain_provider", territoryId: "territory-joal", status: "active" },
    { id: "org-quai-kayar", name: "Gestion du quai de Kayar", organizationType: "landing_site_management", territoryId: "territory-kayar", status: "active" },
  ],
  actors: [
    { id: "actor-mamadou", name: "Mamadou Ndiaye", actorType: "captain", organizationId: "org-piroguiers-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-ibrahima", name: "Ibrahima Fall", actorType: "fisher", organizationId: "org-piroguiers-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-awa", name: "Awa Diouf", actorType: "landing_site_agent", organizationId: "org-quai-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-babacar", name: "Babacar Sarr", actorType: "weigher", organizationId: "org-quai-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-fatou", name: "Fatou Seck", actorType: "buyer", organizationId: "org-mareyeurs-thies", territoryId: "territory-joal", status: "active" },
    { id: "actor-khadija", name: "Khadija Ba", actorType: "processor", organizationId: "org-mareyeurs-thies", territoryId: "territory-joal", status: "active" },
    { id: "actor-cheikh", name: "Cheikh Gueye", actorType: "cold_chain_operator", organizationId: "org-froid-saloum", territoryId: "territory-joal", status: "active" },
    { id: "actor-omar", name: "Omar Sy", actorType: "transporter", organizationId: "org-mareyeurs-thies", territoryId: "territory-joal", status: "active" },
    { id: "actor-aminata", name: "Aminata Cissé", actorType: "territorial_coordinator", organizationId: "org-quai-joal", territoryId: "territory-joal", status: "active" },
    { id: "actor-moussa", name: "Moussa Kane", actorType: "captain", organizationId: "org-piroguiers-joal", territoryId: "territory-kayar", status: "active" },
    { id: "actor-sokhna", name: "Sokhna Mbaye", actorType: "landing_site_agent", organizationId: "org-quai-kayar", territoryId: "territory-kayar", status: "active" },
    { id: "actor-directeur", name: "Direction des pêches artisanales", actorType: "institutional_decision_maker", territoryId: "territory-joal", status: "active" },
  ],
  landingSites: [
    { id: "site-joal-central", name: "Quai central de Joal", territoryId: "territory-joal", managerOrganizationId: "org-quai-joal", capacities: { iceKgAvailable: 2200, coldStorageKgAvailable: 4800, transportKgAvailable: 3000, processingKgAvailable: 1500 }, operationalStatus: "constrained" },
    { id: "site-joal-secondaire", name: "Site secondaire de Joal", territoryId: "territory-joal", managerOrganizationId: "org-quai-joal", capacities: { iceKgAvailable: 900, coldStorageKgAvailable: 1200, transportKgAvailable: 1500, processingKgAvailable: 600 }, operationalStatus: "operational" },
    { id: "site-kayar-central", name: "Quai central de Kayar", territoryId: "territory-kayar", managerOrganizationId: "org-quai-kayar", capacities: { iceKgAvailable: 1800, coldStorageKgAvailable: 2500, transportKgAvailable: 2000, processingKgAvailable: 1000 }, operationalStatus: "operational" },
  ],
  vessels: [
    { id: "vessel-jambar", name: "Jambar", registrationNumber: "SN-JOA-001", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "operational" },
    { id: "vessel-teranga", name: "Teranga", registrationNumber: "SN-JOA-002", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "operational" },
    { id: "vessel-linguere", name: "Linguère", registrationNumber: "SN-JOA-003", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-secondaire", status: "operational" },
    { id: "vessel-ndanaan", name: "Ndaanaan", registrationNumber: "SN-JOA-004", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "maintenance" },
    { id: "vessel-kayar-1", name: "Kayar 1", registrationNumber: "SN-KAY-001", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-kayar-central", status: "operational" },
    { id: "vessel-kayar-2", name: "Kayar 2", registrationNumber: "SN-KAY-002", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-kayar-central", status: "operational" },
    { id: "vessel-sunu-galie", name: "Sunu Gaal", registrationNumber: "SN-JOA-005", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-central", status: "operational" },
    { id: "vessel-baobab", name: "Baobab", registrationNumber: "SN-JOA-006", ownerOrganizationId: "org-piroguiers-joal", homeLandingSiteId: "site-joal-secondaire", status: "operational" },
  ],
  expectedReturns: [
    { id: "return-001", vesselId: "vessel-jambar", expectedLandingSiteId: "site-joal-central", expectedAt: "2026-07-25T08:30:00Z", estimatedCatch: [{ species: "Sardinelle", estimatedWeightKg: 1800 }], serviceNeeds: [{ type: "ice", quantity: 1200, unit: "kg" }, { type: "transport", quantity: 1, unit: "vehicle" }], status: "arrived", createdByActorId: "actor-mamadou", createdAt: "2026-07-25T05:15:00Z" },
    { id: "return-002", vesselId: "vessel-teranga", expectedLandingSiteId: "site-joal-central", expectedAt: "2026-07-25T09:10:00Z", estimatedCatch: [{ species: "Thiof", estimatedWeightKg: 700 }, { species: "Dorade", estimatedWeightKg: 350 }], serviceNeeds: [{ type: "cold_storage", quantity: 700, unit: "kg" }], status: "arrived", createdByActorId: "actor-mamadou", createdAt: "2026-07-25T05:40:00Z" },
    { id: "return-003", vesselId: "vessel-linguere", expectedLandingSiteId: "site-joal-secondaire", expectedAt: "2026-07-25T10:20:00Z", estimatedCatch: [{ species: "Sardinelle", estimatedWeightKg: 1200 }], serviceNeeds: [{ type: "ice", quantity: 700, unit: "kg" }], status: "approaching", createdByActorId: "actor-ibrahima", createdAt: "2026-07-25T06:10:00Z" },
    { id: "return-004", vesselId: "vessel-sunu-galie", expectedLandingSiteId: "site-joal-central", expectedAt: "2026-07-25T11:00:00Z", estimatedCatch: [{ species: "Maquereau", estimatedWeightKg: 1500 }], serviceNeeds: [{ type: "transport", quantity: 2, unit: "vehicle" }], status: "announced", createdByActorId: "actor-mamadou", createdAt: "2026-07-25T06:25:00Z" },
    { id: "return-005", vesselId: "vessel-kayar-1", expectedLandingSiteId: "site-kayar-central", expectedAt: "2026-07-25T09:40:00Z", estimatedCatch: [{ species: "Sardinelle", estimatedWeightKg: 1400 }], serviceNeeds: [{ type: "ice", quantity: 900, unit: "kg" }], status: "arrived", createdByActorId: "actor-moussa", createdAt: "2026-07-25T05:50:00Z" },
    { id: "return-006", vesselId: "vessel-kayar-2", expectedLandingSiteId: "site-kayar-central", expectedAt: "2026-07-25T12:00:00Z", estimatedCatch: [{ species: "Thon", estimatedWeightKg: 900 }], serviceNeeds: [{ type: "cold_storage", quantity: 800, unit: "kg" }], status: "announced", createdByActorId: "actor-moussa", createdAt: "2026-07-25T06:45:00Z" },
  ],
  landings: [
    { id: "landing-001", expectedReturnId: "return-001", vesselId: "vessel-jambar", landingSiteId: "site-joal-central", landedAt: "2026-07-25T08:26:00Z", status: "confirmed", confirmedByActorId: "actor-awa" },
    { id: "landing-002", expectedReturnId: "return-002", vesselId: "vessel-teranga", landingSiteId: "site-joal-central", landedAt: "2026-07-25T09:03:00Z", status: "confirmed", confirmedByActorId: "actor-awa" },
    { id: "landing-003", expectedReturnId: "return-005", vesselId: "vessel-kayar-1", landingSiteId: "site-kayar-central", landedAt: "2026-07-25T09:37:00Z", status: "confirmed", confirmedByActorId: "actor-sokhna" },
    { id: "landing-004", vesselId: "vessel-baobab", landingSiteId: "site-joal-secondaire", landedAt: "2026-07-25T07:50:00Z", status: "confirmed", confirmedByActorId: "actor-awa" },
  ],
  weighings: [
    { id: "weighing-001", landingId: "landing-001", measuredAt: "2026-07-25T08:42:00Z", totalWeightKg: 1720, method: "digital_scale", confidenceLevel: "verified", verifiedByActorId: "actor-babacar" },
    { id: "weighing-002", landingId: "landing-002", measuredAt: "2026-07-25T09:20:00Z", totalWeightKg: 1010, method: "digital_scale", confidenceLevel: "verified", verifiedByActorId: "actor-babacar" },
    { id: "weighing-003", landingId: "landing-003", measuredAt: "2026-07-25T09:55:00Z", totalWeightKg: 1340, method: "mechanical_scale", confidenceLevel: "confirmed", verifiedByActorId: "actor-sokhna" },
    { id: "weighing-004", landingId: "landing-004", measuredAt: "2026-07-25T08:05:00Z", totalWeightKg: 620, method: "digital_scale", confidenceLevel: "verified", verifiedByActorId: "actor-babacar" },
  ],
  lots: [
    { id: "lot-001", landingId: "landing-001", species: "Sardinelle", weightKg: 900, qualityGrade: "standard", conservationStatus: "iced", availabilityStatus: "partially_reserved", askingPricePerKg: 650, currency: "XOF" },
    { id: "lot-002", landingId: "landing-001", species: "Sardinelle", weightKg: 520, qualityGrade: "processing", conservationStatus: "fresh", availabilityStatus: "available", askingPricePerKg: 500, currency: "XOF" },
    { id: "lot-003", landingId: "landing-001", species: "Sardinelle", weightKg: 300, qualityGrade: "standard", conservationStatus: "at_risk", availabilityStatus: "available", askingPricePerKg: 450, currency: "XOF" },
    { id: "lot-004", landingId: "landing-002", species: "Thiof", weightKg: 620, qualityGrade: "premium", conservationStatus: "chilled", availabilityStatus: "reserved", askingPricePerKg: 3200, currency: "XOF" },
    { id: "lot-005", landingId: "landing-002", species: "Dorade", weightKg: 390, qualityGrade: "premium", conservationStatus: "fresh", availabilityStatus: "available", askingPricePerKg: 2800, currency: "XOF" },
    { id: "lot-006", landingId: "landing-003", species: "Sardinelle", weightKg: 800, qualityGrade: "standard", conservationStatus: "iced", availabilityStatus: "available", askingPricePerKg: 600, currency: "XOF" },
    { id: "lot-007", landingId: "landing-003", species: "Sardinelle", weightKg: 540, qualityGrade: "processing", conservationStatus: "fresh", availabilityStatus: "available", askingPricePerKg: 480, currency: "XOF" },
    { id: "lot-008", landingId: "landing-004", species: "Maquereau", weightKg: 280, qualityGrade: "standard", conservationStatus: "fresh", availabilityStatus: "sold", askingPricePerKg: 900, currency: "XOF" },
    { id: "lot-009", landingId: "landing-004", species: "Sardinelle", weightKg: 220, qualityGrade: "processing", conservationStatus: "at_risk", availabilityStatus: "available", askingPricePerKg: 420, currency: "XOF" },
    { id: "lot-010", landingId: "landing-004", species: "Dorade", weightKg: 120, qualityGrade: "premium", conservationStatus: "chilled", availabilityStatus: "sold", askingPricePerKg: 2600, currency: "XOF" },
  ],
  marketNeeds: [
    { id: "need-001", actorId: "actor-fatou", organizationId: "org-mareyeurs-thies", species: "Sardinelle", quantityKg: 1000, territoryId: "territory-joal", neededBy: "2026-07-25T13:00:00Z", status: "partially_matched", relatedLotIds: ["lot-001"] },
    { id: "need-002", actorId: "actor-khadija", organizationId: "org-mareyeurs-thies", species: "Sardinelle", quantityKg: 600, territoryId: "territory-joal", neededBy: "2026-07-25T14:30:00Z", status: "open", relatedLotIds: ["lot-002", "lot-003"] },
    { id: "need-003", actorId: "actor-fatou", organizationId: "org-mareyeurs-thies", species: "Dorade", quantityKg: 300, territoryId: "territory-joal", neededBy: "2026-07-25T12:30:00Z", status: "matched", relatedLotIds: ["lot-005"] },
    { id: "need-004", actorId: "actor-khadija", organizationId: "org-mareyeurs-thies", species: "Sardinelle", quantityKg: 500, territoryId: "territory-kayar", neededBy: "2026-07-25T15:00:00Z", status: "open", relatedLotIds: ["lot-006"] },
  ],
  capacities: [
    { id: "capacity-001", providerOrganizationId: "org-froid-saloum", capacityType: "cold_storage", territoryId: "territory-joal", availableQuantity: 1800, unit: "kg", availableFrom: "2026-07-25T09:30:00Z", status: "partially_available" },
    { id: "capacity-002", providerOrganizationId: "org-froid-saloum", capacityType: "ice", territoryId: "territory-joal", availableQuantity: 900, unit: "kg", availableFrom: "2026-07-25T10:00:00Z", status: "available" },
    { id: "capacity-003", providerOrganizationId: "org-mareyeurs-thies", capacityType: "transport", territoryId: "territory-joal", availableQuantity: 2, unit: "vehicle", availableFrom: "2026-07-25T11:00:00Z", status: "partially_available" },
    { id: "capacity-004", providerOrganizationId: "org-mareyeurs-thies", capacityType: "processing", territoryId: "territory-joal", availableQuantity: 700, unit: "kg", availableFrom: "2026-07-25T12:00:00Z", status: "available" },
    { id: "capacity-005", providerOrganizationId: "org-quai-kayar", capacityType: "ice", territoryId: "territory-kayar", availableQuantity: 1000, unit: "kg", availableFrom: "2026-07-25T10:30:00Z", status: "available" },
  ],
  tensions: [
    { id: "tension-001", tensionType: "cold_storage_shortage", severity: "high", territoryId: "territory-joal", relatedEntityType: "lot", relatedEntityId: "lot-003", description: "300 kg de sardinelle à risque faute de froid disponible au quai central.", status: "coordinating", reportedByActorId: "actor-awa", reportedAt: "2026-07-25T09:10:00Z" },
    { id: "tension-002", tensionType: "transport_shortage", severity: "medium", territoryId: "territory-joal", relatedEntityType: "market_need", relatedEntityId: "need-002", description: "Un véhicule supplémentaire est nécessaire pour acheminer les lots vers l'unité de transformation.", status: "open", reportedByActorId: "actor-fatou", reportedAt: "2026-07-25T09:45:00Z" },
    { id: "tension-003", tensionType: "landing_site_saturation", severity: "medium", territoryId: "territory-kayar", relatedEntityType: "expected_return", relatedEntityId: "return-006", description: "Risque de chevauchement de deux retours avec capacité de manutention limitée.", status: "resolved", reportedByActorId: "actor-sokhna", reportedAt: "2026-07-25T08:55:00Z" },
  ],
  commitments: [
    { id: "commitment-001", tensionId: "tension-001", organizationId: "org-froid-saloum", action: "Réserver 500 kg de capacité froide temporaire.", dueAt: "2026-07-25T10:15:00Z", status: "accepted" },
    { id: "commitment-002", tensionId: "tension-001", actorId: "actor-omar", action: "Acheminer les lots à risque vers l'entrepôt froid.", dueAt: "2026-07-25T10:45:00Z", status: "in_progress" },
    { id: "commitment-003", tensionId: "tension-002", actorId: "actor-omar", action: "Mobiliser un second véhicule léger.", dueAt: "2026-07-25T11:30:00Z", status: "proposed" },
    { id: "commitment-004", tensionId: "tension-003", actorId: "actor-sokhna", action: "Décaler l'arrivée de Kayar 2 de vingt minutes.", dueAt: "2026-07-25T11:40:00Z", status: "completed", completedAt: "2026-07-25T09:20:00Z" },
  ],
  outcomes: [
    { id: "outcome-001", relatedEntityType: "tension", relatedEntityId: "tension-003", outcomeType: "service_continuity_restored", description: "Le décalage du second retour a évité la saturation du quai de Kayar.", valueSavedKg: 900, recordedAt: "2026-07-25T09:25:00Z", evidence: [{ label: "Confirmation du gestionnaire du quai", reference: "commitment-004", confidenceLevel: "confirmed" }] },
    { id: "outcome-002", relatedEntityType: "market_need", relatedEntityId: "need-003", outcomeType: "market_matched", description: "Le besoin de dorade a été couvert par le lot 005.", valueCreated: 840000, currency: "XOF", recordedAt: "2026-07-25T10:05:00Z", evidence: [{ label: "Lot réservé et besoin clôturé", reference: "lot-005", confidenceLevel: "verified" }] },
  ],
};
