import Link from "next/link";

type ActorKind = "referent" | "mareyeur" | "ong" | "institution" | "prive";

const actorConfig: Record<ActorKind, { title: string; kicker: string; promise: string; badge: string; tasks: string[]; expected: string; accent: string }> = {
  referent: { title: "Espace référent pêcheur", kicker: "Référent terrain", promise: "Recevoir les missions envoyées par l’État, ajouter une pièce terrain et confirmer le retour.", badge: "Mission terrain", tasks: ["Vérifier un volume déclaré", "Joindre une photo ou un relevé", "Confirmer un incident ou une espèce sensible"], expected: "Photo, relevé, commentaire terrain", accent: "from-teal-800 via-cyan-700 to-blue-700" },
  mareyeur: { title: "Espace mareyeur", kicker: "Marché et flux", promise: "Recevoir les demandes de complément sur disponibilité, flux, prix ou tension logistique.", badge: "Complément marché", tasks: ["Confirmer disponibilité produit", "Partager une tension logistique", "Renseigner un commentaire de marché"], expected: "Déclaration de flux ou commentaire marché", accent: "from-cyan-800 via-sky-700 to-teal-600" },
  ong: { title: "Espace ONG / partenaire terrain", kicker: "Partenaire programme", promise: "Recevoir les points de coordination, actions de suivi et demandes de compte rendu.", badge: "Coordination programme", tasks: ["Accuser réception d’un point", "Ajouter un compte rendu d’activité", "Signaler un besoin local"], expected: "Compte rendu ou retour de coordination", accent: "from-emerald-700 via-teal-700 to-cyan-700" },
  institution: { title: "Espace institution / bailleur", kicker: "UE · JICA · programme", promise: "Recevoir les notes, demandes d’avis, jalons et justificatifs liés aux programmes.", badge: "Instruction institutionnelle", tasks: ["Lire une note d’arbitrage", "Joindre un avis d’instruction", "Confirmer un jalon programme"], expected: "Avis, rapport, justificatif ou jalon", accent: "from-cyan-900 via-blue-700 to-teal-600" },
  prive: { title: "Espace privé / fournisseur", kicker: "CFAO · équipement · services", promise: "Recevoir les demandes de devis, pièces, planning, maintenance ou livraison.", badge: "Demande fournisseur", tasks: ["Joindre un devis", "Confirmer un planning", "Partager une preuve d’exécution"], expected: "Devis, planning, rapport d’exécution", accent: "from-amber-600 via-cyan-700 to-emerald-600" }
};

export function ActorCoordinationInbox({ actor }: { actor: ActorKind }) {
  const config = actorConfig[actor];
  return <main className="min-h-screen overflow-x-hidden bg-[radial-gradient(circle_at_8%_0%,rgba(34,211,238,0.16),transparent_30%),linear-gradient(180deg,#eefbf8_0%,#f8fbfa_38%,#fff6e4_100%)] text-slate-950">
    <header className="border-b border-cyan-100 bg-white/90 px-4 py-5 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-[94rem] flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><Link href="/espace-prive/etat" className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-800 text-sm font-black text-white">Mb</Link><div><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700">Future inbox acteur · prototype</p><h1 className="text-2xl font-black tracking-tight">{config.title}</h1></div></div><Link href="/espace-prive/etat" className="rounded-full border border-cyan-200 bg-white px-4 py-2 text-sm font-black text-cyan-950 shadow-sm">Retour espace État</Link></div></header>
    <section className="mx-auto grid max-w-[94rem] gap-5 px-4 py-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(20rem,0.85fr)] sm:px-6">
      <section className={`rounded-[2.2rem] bg-gradient-to-br ${config.accent} p-6 text-white shadow-[0_24px_90px_rgba(8,145,178,0.22)]`}><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-100">{config.kicker}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Les actions envoyées par l’État arrivent ici</h2><p className="mt-4 max-w-3xl text-sm font-bold leading-6 text-cyan-50">{config.promise}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{["Reçu", "À compléter", "Retour envoyé"].map((step, index) => <div key={step} className="rounded-2xl bg-white/14 p-3 ring-1 ring-white/20"><p className="text-xs font-black uppercase tracking-[0.14em] text-cyan-50">0{index + 1}</p><p className="mt-1 font-black">{step}</p></div>)}</div></section>
      <aside className="grid gap-5"><section className="rounded-[2rem] border border-cyan-100 bg-white/94 p-5 shadow-sm"><p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-cyan-800">Action entrante mockée</p><div className="mt-3 rounded-2xl bg-cyan-50/70 p-4"><p className="text-lg font-black text-cyan-950">{config.badge}</p><p className="mt-2 text-sm font-bold leading-6 text-slate-600">Demande créée depuis l’espace État. Le destinataire complète la pièce attendue et l’État suit le retour.</p></div><div className="mt-4 grid gap-2 text-sm font-bold text-slate-700"><p><span className="text-slate-500">Pièce attendue : </span>{config.expected}</p><p><span className="text-slate-500">Statut : </span>en attente de retour</p><p><span className="text-slate-500">Journal : </span>visible côté État</p></div></section><section className="rounded-[2rem] border border-cyan-100 bg-white/94 p-5 shadow-sm"><p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-cyan-800">Actions du destinataire</p><div className="mt-4 grid gap-3">{config.tasks.map((task) => <button key={task} className="rounded-2xl border border-cyan-100 bg-cyan-50/65 p-3 text-left text-sm font-black text-cyan-950">{task}</button>)}</div></section></aside>
    </section>
  </main>;
}
