import Link from "next/link";

type ActorKind = "referent" | "mareyeur" | "ong" | "institution" | "prive";

const actorConfig: Record<ActorKind, { title: string; kicker: string; role: string; promise: string; badge: string; tasks: string[]; expected: string; accent: string }> = {
  referent: { title: "Espace destinataire · Référent pêcheur", kicker: "Référent terrain", role: "Je suis le relais terrain. Je reçois une mission envoyée par l’État et je renvoie une preuve terrain.", promise: "Cet espace n’est pas un cockpit État. Il sert au référent à répondre à une demande reçue : vérifier, joindre une pièce, confirmer le retour.", badge: "Mission reçue depuis l’État", tasks: ["Vérifier un volume déclaré", "Joindre une photo ou un relevé", "Confirmer un incident ou une espèce sensible"], expected: "Photo, relevé, commentaire terrain", accent: "from-teal-800 via-cyan-700 to-blue-700" },
  mareyeur: { title: "Espace destinataire · Mareyeur", kicker: "Marché et flux", role: "Je suis un acteur de flux. Je reçois une demande de complément sur marché, disponibilité, prix ou tension logistique.", promise: "Cet espace sert au mareyeur à répondre à une demande venant du cockpit État, pas à piloter l’action publique.", badge: "Demande marché reçue", tasks: ["Confirmer disponibilité produit", "Partager une tension logistique", "Renseigner un commentaire de marché"], expected: "Déclaration de flux ou commentaire marché", accent: "from-cyan-800 via-sky-700 to-teal-600" },
  ong: { title: "Espace destinataire · ONG partenaire", kicker: "Partenaire programme", role: "Je suis une ONG ou un partenaire terrain. Je reçois un point de coordination et je renvoie un compte rendu.", promise: "Cet espace matérialise la coordination sortante : l’État partage un point, le partenaire complète, Mbàmbulaan garde le suivi.", badge: "Point de coordination reçu", tasks: ["Accuser réception d’un point", "Ajouter un compte rendu d’activité", "Signaler un besoin local"], expected: "Compte rendu ou retour de coordination", accent: "from-emerald-700 via-teal-700 to-cyan-700" },
  institution: { title: "Espace destinataire · Institution / bailleur", kicker: "UE · JICA · programme", role: "Je suis une institution, un bailleur ou un programme. Je reçois une note, un jalon ou une demande d’avis.", promise: "Cet espace sert à répondre à une instruction envoyée par l’État : avis, justificatif, rapport ou confirmation de jalon.", badge: "Instruction reçue depuis l’État", tasks: ["Lire une note d’arbitrage", "Joindre un avis d’instruction", "Confirmer un jalon programme"], expected: "Avis, rapport, justificatif ou jalon", accent: "from-cyan-900 via-blue-700 to-teal-600" },
  prive: { title: "Espace destinataire · Privé / fournisseur", kicker: "CFAO · équipement · services", role: "Je suis un fournisseur ou prestataire privé. Je reçois une demande de devis, planning, maintenance ou preuve d’exécution.", promise: "Cet espace montre comment une action État devient une demande opérationnelle adressée à un acteur privé.", badge: "Demande fournisseur reçue", tasks: ["Joindre un devis", "Confirmer un planning", "Partager une preuve d’exécution"], expected: "Devis, planning, rapport d’exécution", accent: "from-amber-600 via-cyan-700 to-emerald-600" }
};

export function ActorCoordinationInbox({ actor }: { actor: ActorKind }) {
  const config = actorConfig[actor];
  return <main className="min-h-screen overflow-x-hidden bg-[radial-gradient(circle_at_8%_0%,rgba(34,211,238,0.16),transparent_30%),linear-gradient(180deg,#eefbf8_0%,#f8fbfa_38%,#fff6e4_100%)] text-slate-950">
    <header className="border-b border-cyan-100 bg-white/90 px-4 py-5 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-[94rem] flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><Link href="/espace-prive/etat" className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-800 text-sm font-black text-white">Mb</Link><div><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700">Espace partenaire destinataire · prototype</p><h1 className="text-2xl font-black tracking-tight">{config.title}</h1></div></div><Link href="/espace-prive/etat" className="rounded-full border border-cyan-200 bg-white px-4 py-2 text-sm font-black text-cyan-950 shadow-sm">Retour cockpit État</Link></div></header>
    <section className="mx-auto grid max-w-[94rem] gap-5 px-4 py-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(20rem,0.85fr)] sm:px-6">
      <section className={`rounded-[2.2rem] bg-gradient-to-br ${config.accent} p-6 text-white shadow-[0_24px_90px_rgba(8,145,178,0.22)]`}><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-100">{config.kicker}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Ici, le partenaire répond à l’État</h2><p className="mt-4 max-w-3xl text-sm font-bold leading-6 text-cyan-50">{config.role}</p><p className="mt-3 max-w-3xl rounded-2xl bg-white/14 p-4 text-sm font-bold leading-6 text-cyan-50 ring-1 ring-white/20">{config.promise}</p><div className="mt-6 grid gap-3 sm:grid-cols-4">{["Demande reçue", "Pièce à joindre", "Réponse envoyée", "État notifié"].map((step, index) => <div key={step} className="rounded-2xl bg-white/14 p-3 ring-1 ring-white/20"><p className="text-xs font-black uppercase tracking-[0.14em] text-cyan-50">0{index + 1}</p><p className="mt-1 font-black">{step}</p></div>)}</div></section>
      <aside className="grid gap-5"><section className="rounded-[2rem] border border-cyan-100 bg-white/94 p-5 shadow-sm"><p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-cyan-800">Demande entrante depuis l’État</p><div className="mt-3 rounded-2xl bg-cyan-50/70 p-4"><p className="text-lg font-black text-cyan-950">{config.badge}</p><p className="mt-2 text-sm font-bold leading-6 text-slate-600">Cette page représente l’espace du destinataire. Il complète la pièce attendue, envoie sa réponse, puis l’espace État voit le retour.</p></div><div className="mt-4 grid gap-2 text-sm font-bold text-slate-700"><p><span className="text-slate-500">Rôle de cet espace : </span>répondre, compléter, joindre une pièce</p><p><span className="text-slate-500">Pièce attendue : </span>{config.expected}</p><p><span className="text-slate-500">Statut : </span>en attente de réponse partenaire</p><p><span className="text-slate-500">Retour : </span>visible dans le cockpit État</p></div></section><section className="rounded-[2rem] border border-cyan-100 bg-white/94 p-5 shadow-sm"><p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-cyan-800">Actions du partenaire</p><div className="mt-4 grid gap-3">{config.tasks.map((task) => <button key={task} className="rounded-2xl border border-cyan-100 bg-cyan-50/65 p-3 text-left text-sm font-black text-cyan-950">{task}</button>)}</div></section></aside>
    </section>
  </main>;
}
