"use client";

import { useState } from "react";
import type { DataTrustLevel } from "@/data/ministryControlTowerData";
import type { DecisionRecord, FundingDossierRecord, PartnerRelationship, SignalRecord, VerificationTask, ZoneReportRecord } from "@/data/ministryValueJourneyData";
import { formatFcfa } from "@/data/ministryValueJourneyData";
import { DataTrustBadge, primaryButton, secondaryButton, StatusBadge } from "./MinistryControlTowerParts";

export type DemoRole = "Ministère" | "Direction régionale" | "Partenaire / Bailleur";

export function RoleFrame({ role, onChange }: { role: DemoRole; onChange: (role: DemoRole) => void }) {
  const explanation = role === "Ministère" ? "Synthèses consolidées, arbitrages et financements. Les signaux bruts restent au niveau régional." : role === "Direction régionale" ? "Signalements, vérifications, qualifications et rapports de zone." : "Dossiers finançables, preuves d’impact et valeur biodiversité, sans bruit opérationnel brut.";
  return <section className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--mb-neutral-200)] bg-white px-3 py-2"><div><p className="font-mono text-[8px] uppercase text-[var(--mb-neutral-400)]">Cadre de démonstration</p><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">{explanation}</p></div><label className="flex items-center gap-2 text-[9px] font-bold text-[var(--mb-neutral-600)]">Vue actuelle<select value={role} onChange={(event) => onChange(event.target.value as DemoRole)} className="h-8 rounded-[3px] border border-[var(--mb-neutral-200)] bg-white px-2 text-[10px] font-semibold text-[var(--mb-navy-900)]"><option>Ministère</option><option>Direction régionale</option><option>Partenaire / Bailleur</option></select></label></section>;
}

export function FundingRegister({ dossiers, onConfirmTransmission, onRecordResponse }: { dossiers: FundingDossierRecord[]; onConfirmTransmission: (id: string, date: string, responsible: string) => void; onRecordResponse: (id: string) => void }) {
  const [confirmingId, setConfirmingId] = useState<string | null>(null);
  const [date, setDate] = useState("2026-07-15");
  const [responsible, setResponsible] = useState("Cellule partenariats");
  return <section className="border border-[var(--mb-neutral-200)] bg-white"><header className="border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><h2 className="text-[11px] font-bold text-[var(--mb-navy-900)]">Registre de financement</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">Un dossier constitué n’est jamais considéré transmis sans confirmation humaine.</p></header>{dossiers.length ? <div className="divide-y divide-[var(--mb-neutral-100)]">{dossiers.map((dossier) => <article key={dossier.id} className="grid gap-3 px-3 py-3 xl:grid-cols-[minmax(0,1.3fr)_minmax(10rem,.7fr)_auto]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-[10px] font-semibold">{dossier.title}</h3><DataTrustBadge level={dossier.trustLevel} compact /></div><p className="mt-1 font-mono text-[9px] text-[var(--mb-neutral-600)]">{formatFcfa(dossier.amountRequested)} · {dossier.targetPartner}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-400)]">{dossier.owner} · mis à jour {dossier.updatedAt}</p></div><div><p className="text-[9px] font-semibold text-[var(--mb-ocean-600)]">{dossier.status}{dossier.transmittedAt ? ` le ${dossier.transmittedAt}` : " — non encore transmis"}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{dossier.nextAction}</p></div><div className="flex flex-wrap items-center gap-2">{dossier.status === "Transmission à confirmer" ? <button onClick={() => setConfirmingId(dossier.id)} className={primaryButton}>Confirmer la transmission</button> : dossier.status === "Transmis" ? <button onClick={() => onRecordResponse(dossier.id)} className={secondaryButton}>Enregistrer une réponse</button> : null}</div>{confirmingId === dossier.id ? <form onSubmit={(event) => { event.preventDefault(); onConfirmTransmission(dossier.id, date, responsible); setConfirmingId(null); }} className="grid gap-2 border-l-2 border-[var(--mb-amber-500)] bg-[var(--mb-offwhite)] p-3 xl:col-span-3 sm:grid-cols-[10rem_minmax(12rem,1fr)_auto]"><label className="grid gap-1 text-[8px] font-bold uppercase text-[var(--mb-neutral-600)]">Date<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} className="h-8 border border-[var(--mb-neutral-200)] bg-white px-2 text-[10px]" /></label><label className="grid gap-1 text-[8px] font-bold uppercase text-[var(--mb-neutral-600)]">Responsable<input required value={responsible} onChange={(event) => setResponsible(event.target.value)} className="h-8 border border-[var(--mb-neutral-200)] bg-white px-2 text-[10px]" /></label><button className={`${primaryButton} self-end`}>J’ai transmis ce dossier</button></form> : null}</article>)}</div> : <EmptyRegister text="Aucun dossier constitué. La création d’un dossier l’ajoutera ici avec le statut Transmission à confirmer." />}</section>;
}

export function PartnerRegister({ relationships, onRecordResponse }: { relationships: PartnerRelationship[]; onRecordResponse: (id: string) => void }) {
  return <section className="border border-[var(--mb-neutral-200)] bg-white"><header className="border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><h2 className="text-[11px] font-bold">Partenaires & suivi</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">Relations utiles au dossier, sans messagerie ni CRM simulé.</p></header>{relationships.length ? <div className="divide-y divide-[var(--mb-neutral-100)]">{relationships.map((relationship) => <article key={relationship.id} className="grid gap-2 px-3 py-3 sm:grid-cols-[minmax(0,1fr)_10rem_auto]"><div><h3 className="text-[10px] font-semibold">{relationship.partnerName}</h3><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{relationship.category} · {relationship.compatibilityReason}</p><p className="mt-1 font-mono text-[8px] text-[var(--mb-neutral-400)]">{relationship.interestTags.join(" · ")}</p></div><div><p className="text-[9px] font-semibold text-[var(--mb-ocean-600)]">{relationship.status}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">Relance : {relationship.followUpDueDate}</p></div><button onClick={() => onRecordResponse(relationship.id)} className={secondaryButton}>Enregistrer une réponse</button></article>)}</div> : <EmptyRegister text="Aucune sollicitation préparée. Une relation apparaîtra après sélection d’un partenaire." />}</section>;
}

export function DecisionRegister({ decisions, onAdvance }: { decisions: DecisionRecord[]; onAdvance: (id: string) => void }) {
  return <section className="border border-[var(--mb-neutral-200)] bg-white"><header className="border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><h2 className="text-[11px] font-bold">Registre notes & décisions</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">La note crée des recommandations suivies jusqu’à l’exécution.</p></header>{decisions.length ? <div className="divide-y divide-[var(--mb-neutral-100)]">{decisions.map((decision) => <article key={decision.id} className="grid gap-2 px-3 py-3 lg:grid-cols-[minmax(0,1.3fr)_8rem_minmax(10rem,.7fr)_auto]"><div><p className="text-[10px] font-semibold">{decision.recommendation}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{decision.noteTitle} · source : {decision.source}</p></div><StatusBadge level={decision.priority === "Urgente" ? "urgent" : decision.priority === "Prioritaire" ? "surveillance" : "normal"}>{decision.priority}</StatusBadge><div><p className="text-[9px] font-semibold text-[var(--mb-ocean-600)]">{decision.status}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{decision.owner} · {decision.nextAction}</p></div>{decision.status === "Exécutée" ? <span className="self-center text-[8px] font-bold text-[var(--mb-green-600)]">Cycle clôturé</span> : <button onClick={() => onAdvance(decision.id)} className={secondaryButton}>{decision.status === "À arbitrer" ? "Enregistrer l’arbitrage" : "Faire avancer"}</button>}</article>)}</div> : <EmptyRegister text="Aucune note générée. Une note au Ministre créera ici ses recommandations à arbitrer." />}</section>;
}

export function ReportRegister({ reports }: { reports: ZoneReportRecord[] }) {
  return <section className="border border-[var(--mb-neutral-200)] bg-white"><header className="border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><h2 className="text-[11px] font-bold">Rapports de zone générés</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">Chaque rapport fige une situation datée sans modifier le statut des entités.</p></header>{reports.length ? <div className="divide-y divide-[var(--mb-neutral-100)]">{reports.map((report) => <article key={report.id} className="grid gap-2 px-3 py-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[10px] font-semibold">{report.title}</p><DataTrustBadge level={report.trustLevel} compact /></div><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{report.zone} · {report.period} · {report.linkedObjectsCount} objets liés</p></div><p className="text-right font-mono text-[8px] text-[var(--mb-neutral-400)]">{report.generatedAt}<br />{report.author}</p></article>)}</div> : <EmptyRegister text="Aucun rapport généré pour cette session." />}</section>;
}

export function WhatsAppBridge({ tasks, signals, onPrepare, onCompleteVerification, onQualifySignal }: { tasks: VerificationTask[]; signals: SignalRecord[]; onPrepare: (template: string) => void; onCompleteVerification: (id: string) => void; onQualifySignal: (id: string) => void }) {
  const templates = ["SIGNALEMENT · [quai] · [description] · [photo]", "VÉRIFICATION DEMANDÉE · [entité] · Merci de confirmer sur place et répondre avec une photo.", "RETOUR VÉRIFICATION · [entité] · Constat : [texte] · [photo]", "DÉBARQUEMENT · [quai] · Pirogue [id] · Espèces : [liste] · Volume estimé : [quantité]"];
  return <section className="border border-[var(--mb-neutral-200)] bg-white"><header className="flex flex-wrap items-start justify-between gap-2 border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><div><h2 className="text-[11px] font-bold">Pont terrain · WhatsApp structuré</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">Canal pilote simulé — envoi réel non connecté dans cette démo.</p></div><button onClick={() => onPrepare(templates[1])} className={secondaryButton}>Préparer un message WhatsApp</button></header><div className="grid lg:grid-cols-2"><div className="border-b border-[var(--mb-neutral-200)] lg:border-b-0 lg:border-r"><p className="border-b border-[var(--mb-neutral-100)] px-3 py-2 font-mono text-[8px] uppercase text-[var(--mb-neutral-400)]">Vérifications demandées</p>{tasks.length ? tasks.slice(0, 4).map((task) => <div key={task.id} className="border-b border-[var(--mb-neutral-100)] px-3 py-2.5"><div className="flex items-start justify-between gap-2"><div><p className="text-[9px] font-semibold">{task.target}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{task.recipient} · {task.channel} · avant {task.dueDate}</p></div><span className="text-[8px] font-bold text-[var(--mb-ocean-600)]">{task.status}</span></div><div className="mt-2 flex gap-2"><button onClick={() => onPrepare(task.message)} className="text-[8px] font-bold text-[var(--mb-ocean-600)]">Copier le message</button>{task.status !== "Vérifiée" ? <button onClick={() => onCompleteVerification(task.id)} className="text-[8px] font-bold text-[var(--mb-green-600)]">Déposer le constat</button> : null}</div></div>) : <EmptyRegister text="Aucune vérification demandée." />}</div><div><p className="border-b border-[var(--mb-neutral-100)] px-3 py-2 font-mono text-[8px] uppercase text-[var(--mb-neutral-400)]">Signalements reçus</p>{signals.length ? signals.slice(0, 4).map((signal) => <div key={signal.id} className="border-b border-[var(--mb-neutral-100)] px-3 py-2.5"><div className="flex items-start justify-between gap-2"><div><p className="text-[9px] font-semibold">{signal.title}</p><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{signal.sender} → {signal.receivingCell} · {signal.attachmentHint}</p></div><DataTrustBadge level={signal.trustLevel as DataTrustLevel} compact /></div>{signal.status === "Signalé" ? <button onClick={() => onQualifySignal(signal.id)} className="mt-2 text-[8px] font-bold text-[var(--mb-ocean-600)]">Qualifier ce signalement</button> : <p className="mt-2 text-[8px] font-semibold text-[var(--mb-green-600)]">{signal.status}</p>}</div>) : <EmptyRegister text="Aucun signalement reçu pendant cette session." />}</div></div></section>;
}

function EmptyRegister({ text }: { text: string }) {
  return <p className="px-3 py-4 text-[9px] leading-4 text-[var(--mb-neutral-600)]">{text}</p>;
}
