"use client";

import { communityNeeds, communityProjects, quays, trainingPrograms, type MapAlert } from "@/data/ministryControlTowerData";
import { fundingCoverageByOpportunity, type FundingDossierRecord, type FundingOpportunity, type GeneratedArtifact } from "@/data/ministryValueJourneyData";
import type { DossierOperationnel } from "@/lib/ministryOperationalDossiers";
import { draftArbitrationNote } from "@/lib/mbambulaanAssistant";
import { DataTrustBadge, primaryButton, secondaryButton, StatusBadge, WorkspaceHeader } from "./MinistryControlTowerParts";

type Props = {
  assistanceEnabled: boolean;
  dossiers: DossierOperationnel[];
  alerts: MapAlert[];
  artifacts: GeneratedArtifact[];
  opportunities: FundingOpportunity[];
  fundingDossiers: FundingDossierRecord[];
  onViewAtlas: (quayId: string) => void;
  onOpenDossier: (dossier: DossierOperationnel) => void;
  onOpenDossiers: () => void;
  onOpenCommunity: () => void;
};

export function MinistryPilotageView({ assistanceEnabled, dossiers, alerts, artifacts, opportunities, fundingDossiers, onViewAtlas, onOpenDossier, onOpenDossiers, onOpenCommunity }: Props) {
  const kayar = dossiers.find((dossier) => dossier.id === "VER-2026-0142") ?? dossiers[0];
  const joalOpportunity = opportunities.find((opportunity) => opportunity.id === "fund-op-1");
  const joalDossier = dossiers.find((dossier) => dossier.type === "Besoin filière" && (dossier.sourceId === joalOpportunity?.id || dossier.linkedObject === joalOpportunity?.title));
  const activeDossiers = dossiers.filter((dossier) => dossier.workStatus !== "Terminé");
  const decisions = dossiers.filter((dossier) => dossier.type === "Décision institutionnelle" && dossier.workStatus !== "Terminé");
  const qualifiedNeeds = communityNeeds.filter((need) => ["verified", "consolidated"].includes(need.trustLevel));
  const activePrograms = [...communityProjects, ...trainingPrograms].filter((program) => !["À compléter", "À financer"].includes(program.status));
  const totalBudget = opportunities.reduce((sum, opportunity) => sum + opportunity.estimatedAmount, 0);
  const coveredBudget = opportunities.reduce((sum, opportunity) => sum + (fundingCoverageByOpportunity[opportunity.id]?.coveredAmount ?? 0), 0);
  const remainingBudget = Math.max(totalBudget - coveredBudget, 0);
  const trustedQuays = quays.filter((quay) => ["verified", "consolidated"].includes(quay.trustLevel)).length;
  const note = kayar ? draftArbitrationNote(kayar) : null;
  const maxVolume = Math.max(...quays.map((quay) => quay.volumeTons), 1);
  const attentionByLevel = [
    { label: "Critiques", value: quays.filter((quay) => quay.level === "urgent").length, color: "bg-[var(--mb-red-600)]" },
    { label: "Vigilance", value: quays.filter((quay) => quay.level === "surveillance").length, color: "bg-[var(--mb-amber-500)]" },
    { label: "Stables", value: quays.filter((quay) => quay.level === "normal").length, color: "bg-[var(--mb-green-600)]" },
  ];

  return <section className="min-h-full bg-[var(--mb-offwhite)]">
    <WorkspaceHeader title="Pilotage" question="Lire la situation nationale, concentrer l’action et décider avec des preuves." scope="Nationale" onScopeChange={() => undefined} onExport={() => undefined} />
    <div className="border-b border-[var(--mb-neutral-200)] bg-[var(--mb-navy-900)] px-4 py-7 text-white sm:px-6">
      <div className="mx-auto max-w-[86rem]"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[var(--mb-ocean-400)]">Situation nationale · démonstration</p><div className="mt-3 grid gap-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><h2 className="max-w-4xl text-[26px] font-semibold leading-tight">Voir la filière. Écouter le terrain. Transformer les besoins en programmes finançables. Décider avec des preuves.</h2><p className="mt-3 max-w-3xl text-[11px] leading-5 text-white/70">{activeDossiers.length} dossiers demandent une action, {qualifiedNeeds.length} besoins communautaires sont qualifiés et {formatCompact(remainingBudget)} restent à mobiliser sur les opportunités simulées.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => kayar && onOpenDossier(kayar)} className="h-10 bg-[var(--mb-sand-300)] px-4 text-[11px] font-bold text-[var(--mb-navy-900)]">Ouvrir la priorité Kayar</button><button onClick={onOpenCommunity} className="h-10 border border-white/25 px-4 text-[11px] font-bold text-white">Voir les besoins et programmes</button></div></div><p className="mt-5 border-t border-white/10 pt-3 text-[10px] text-white/55">Sources locales simulées : postes reconnus, appels, WhatsApp manuel, agents territoriaux, formulaires et pièces documentaires. Validation humaine obligatoire.</p></div>
    </div>

    <div className="mx-auto max-w-[86rem] px-4 py-5 sm:px-6">
      <section className="grid grid-cols-2 border border-[var(--mb-neutral-200)] bg-white md:grid-cols-3 xl:grid-cols-6"><PilotMetric label="Quais suivis" value={String(quays.length)} detail="Couverture littorale" action="Voir l’Atlas" onClick={() => onViewAtlas("kayar")} /><PilotMetric label="Situations en attention" value={String(alerts.length)} detail="À qualifier ou traiter" action="Ouvrir les dossiers" onClick={onOpenDossiers} /><PilotMetric label="Besoins qualifiés" value={String(qualifiedNeeds.length)} detail="Sources vérifiées" action="Voir les besoins" onClick={onOpenCommunity} /><PilotMetric label="Programmes actifs" value={String(activePrograms.length)} detail="Projets et formations" action="Voir le portefeuille" onClick={onOpenCommunity} /><PilotMetric label="Reste à mobiliser" value={formatCompact(remainingBudget)} detail="Financements simulés" action="Voir les financements" onClick={onOpenCommunity} /><PilotMetric label="Décisions à arbitrer" value={String(decisions.length)} detail="Décisions institutionnelles" action="Voir les dossiers" onClick={onOpenDossiers} /></section>

      <section className="mt-5 border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Action prioritaire" title="Deux parcours, une même chaîne de preuve" helper="Kayar démontre la capacité opérationnelle. Joal–Mbour démontre la structuration communautaire et financière." /><div className="grid gap-px bg-[var(--mb-neutral-200)] lg:grid-cols-2"><PriorityPath eyebrow="Parcours opérationnel" title="Kayar · écart de pesée" description="Le constat doit être vérifié avant consolidation du rapport de zone." result="Résultat : une preuve validée, une décision tracée et un rapport relu." action={kayar?.nextAction ?? "Ouvrir le dossier"} onClick={() => kayar && onOpenDossier(kayar)} trust={kayar?.pieces.some((piece) => piece.status === "Attendue") ? "declared" : "verified"} /><PriorityPath eyebrow="Parcours communautaire & financier" title="Joal–Mbour · chaîne de froid" description="680 bénéficiaires, un programme structuré et un partenaire compatible à instruire." result={`Résultat : un dossier de financement de ${formatCompact(joalOpportunity?.estimatedAmount ?? 0)} prêt à relire.`} action={joalDossier ? "Ouvrir le dossier de financement" : "Voir le programme"} onClick={() => joalDossier ? onOpenDossier(joalDossier) : onOpenCommunity()} trust="verified" /></div></section>

      <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(22rem,.75fr)]">
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Activité et couverture territoriale" title="Volumes déclarés par quai" helper="Une lecture directe des volumes, sans dupliquer l’Atlas." /><div className="grid gap-3 p-4">{quays.map((quay) => <button key={quay.id} onClick={() => onViewAtlas(quay.id)} className="grid grid-cols-[7rem_minmax(0,1fr)_4rem] items-center gap-3 text-left"><span className="truncate text-[10px] font-semibold">{quay.name}</span><span className="h-2 bg-[var(--mb-neutral-100)]"><span className="block h-full bg-[var(--mb-ocean-600)]" style={{ width: `${Math.max(5, quay.volumeTons / maxVolume * 100)}%` }} /></span><strong className="text-right font-mono text-[10px]">{quay.volumeTons.toFixed(1)} t</strong></button>)}</div></section>
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Situations en attention" title="Répartition territoriale" helper="Les niveaux orientent l’instruction, ils ne remplacent pas la décision." /><div className="grid gap-4 p-4">{attentionByLevel.map((item) => <div key={item.label}><div className="flex justify-between text-[10px]"><span className="font-semibold">{item.label}</span><strong className="font-mono">{item.value} quai(s)</strong></div><div className="mt-2 h-2 bg-[var(--mb-neutral-100)]"><div className={`h-full ${item.color}`} style={{ width: `${Math.max(item.value / quays.length * 100, 3)}%` }} /></div></div>)}<p className="border-l-2 border-[var(--mb-ocean-400)] pl-3 text-[10px] leading-5 text-[var(--mb-neutral-600)]">{trustedQuays} quais disposent d’informations vérifiées ou consolidées.</p></div></section>
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-2">
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Communautés et programmes" title="Du besoin signalé au programme finançable" helper="Progression agrégée des besoins, avec une action claire vers le portefeuille." /><div className="grid grid-cols-5 border-b border-[var(--mb-neutral-100)]"><Stage value={communityNeeds.length} label="Signalés" /><Stage value={communityNeeds.filter((need) => ["verified", "consolidated"].includes(need.trustLevel)).length} label="Vérifiés" /><Stage value={qualifiedNeeds.length} label="Qualifiés" /><Stage value={communityProjects.length} label="Programmés" /><Stage value={opportunities.filter((item) => item.status !== "À qualifier").length} label="Finançables" /></div><div className="p-4"><p className="text-[10px] leading-5 text-[var(--mb-neutral-600)]">La chaîne de froid Joal–Mbour relie le besoin terrain, le programme, les bénéficiaires, le budget et les preuves dans un même dossier.</p><button onClick={onOpenCommunity} className={`${primaryButton} mt-3`}>Voir les besoins et programmes</button></div></section>
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Financement et impact" title="Couvert versus reste à mobiliser" helper="Montants indicatifs sur données simulées, sans transmission automatique." /><div className="p-4"><div className="flex justify-between gap-4 text-[10px]"><span><strong className="block font-mono text-[18px] text-[var(--mb-green-600)]">{formatCompact(coveredBudget)}</strong>couvert ou identifié</span><span className="text-right"><strong className="block font-mono text-[18px] text-[var(--mb-navy-900)]">{formatCompact(remainingBudget)}</strong>reste à mobiliser</span></div><div className="mt-4 h-3 bg-[var(--mb-neutral-100)]"><div className="h-full bg-[var(--mb-green-600)]" style={{ width: `${totalBudget ? coveredBudget / totalBudget * 100 : 0}%` }} /></div><p className="mt-4 text-[10px] leading-5 text-[var(--mb-neutral-600)]">{opportunities.reduce((sum, item) => sum + item.beneficiaries, 0).toLocaleString("fr-FR")} bénéficiaires potentiels sur {opportunities.length} opportunités structurées.</p><button onClick={onOpenCommunity} className={`${secondaryButton} mt-3`}>Ouvrir les financements</button></div></section>
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,.8fr)]">
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Décisions et documents récents" title="Sorties prêtes à relire" helper="Chaque sortie reste reliée à son dossier et à ses sources." /><div className="divide-y divide-[var(--mb-neutral-100)]">{artifacts.filter((artifact) => ["export-zone", "note", "funding", "verification"].includes(artifact.kind)).slice(0, 4).map((artifact) => <article key={artifact.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div><h3 className="text-[11px] font-semibold">{artifact.title}</h3><p className="mt-1 text-[10px] text-[var(--mb-neutral-600)]">{artifact.scope} · {artifact.createdAt} · validateur : {artifact.validator}</p></div><span className="self-center text-[10px] font-bold text-[var(--mb-ocean-600)]">Document local prêt à relire</span></article>)}{!artifacts.length ? <p className="p-4 text-[10px] text-[var(--mb-neutral-500)]">Aucun document récent.</p> : null}</div></section>
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader eyebrow="Confiance et fraîcheur" title="Ce qui fonde la lecture" helper="Aucune source serveur n’est simulée." /><div className="grid gap-4 p-4"><CoverageLine label="Quais couverts" value={`${quays.length} / ${quays.length}`} progress={100} /><CoverageLine label="Informations vérifiées ou consolidées" value={`${trustedQuays} / ${quays.length}`} progress={trustedQuays / quays.length * 100} /><CoverageLine label="Dossiers avec pièces disponibles" value={`${dossiers.filter((item) => item.pieces.some((piece) => piece.status === "Disponible")).length} / ${dossiers.length}`} progress={dossiers.filter((item) => item.pieces.some((piece) => piece.status === "Disponible")).length / Math.max(dossiers.length, 1) * 100} /><button onClick={onOpenDossiers} className={secondaryButton}>Consulter les dossiers et preuves</button></div></section>
      </div>

      {assistanceEnabled && note ? <section className="mt-5 border-l-2 border-[var(--mb-ocean-600)] bg-[var(--mb-foam)] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.08em] text-[var(--mb-ocean-600)]">Proposition à valider</p><h3 className="mt-2 text-[13px] font-semibold">{note.subject}</h3><p className="mt-2 text-[10px] leading-5 text-[var(--mb-neutral-600)]">{note.recommendation}</p><p className="mt-3 text-[10px] text-[var(--mb-neutral-500)]">Sources : {note.sources.join(" · ") || "dossier local"}. Assistance locale déterministe, aucune API. Validation humaine obligatoire.</p><button onClick={() => kayar && onOpenDossier(kayar)} className={`${secondaryButton} mt-3`}>Relire les sources dans le dossier</button></section> : null}
    </div>
  </section>;
}

function PilotMetric({ label, value, detail, action, onClick }: { label: string; value: string; detail: string; action: string; onClick: () => void }) { return <button onClick={onClick} className="min-w-0 border-b border-r border-[var(--mb-neutral-200)] p-3 text-left hover:bg-[var(--mb-offwhite)]"><span className="block text-[10px] font-semibold text-[var(--mb-neutral-600)]">{label}</span><strong className="mt-2 block truncate font-mono text-[20px] text-[var(--mb-navy-900)]">{value}</strong><span className="mt-1 block text-[9px] text-[var(--mb-neutral-500)]">{detail}</span><span className="mt-2 block text-[10px] font-bold text-[var(--mb-ocean-600)]">{action} →</span></button>; }
function SectionHeader({ eyebrow, title, helper }: { eyebrow: string; title: string; helper: string }) { return <header className="border-b border-[var(--mb-neutral-200)] px-4 py-3"><p className="text-[9px] font-bold uppercase tracking-[0.08em] text-[var(--mb-ocean-600)]">{eyebrow}</p><h2 className="mt-1 text-[14px] font-semibold text-[var(--mb-navy-900)]">{title}</h2><p className="mt-1 text-[10px] leading-4 text-[var(--mb-neutral-600)]">{helper}</p></header>; }
function PriorityPath({ eyebrow, title, description, result, action, onClick, trust }: { eyebrow: string; title: string; description: string; result: string; action: string; onClick: () => void; trust: "declared" | "verified" }) { return <article className="bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[9px] font-bold uppercase tracking-[0.08em] text-[var(--mb-ocean-600)]">{eyebrow}</p><DataTrustBadge level={trust} compact /></div><h3 className="mt-3 text-[16px] font-semibold text-[var(--mb-navy-900)]">{title}</h3><p className="mt-2 text-[10px] leading-5 text-[var(--mb-neutral-600)]">{description}</p><p className="mt-3 border-l-2 border-[var(--mb-ocean-400)] pl-3 text-[10px] font-semibold leading-5 text-[var(--mb-navy-900)]">{result}</p><button onClick={onClick} className={`${primaryButton} mt-4`}>{action}</button></article>; }
function Stage({ value, label }: { value: number; label: string }) { return <div className="min-w-0 border-r border-[var(--mb-neutral-100)] p-3 text-center last:border-r-0"><strong className="font-mono text-[17px] text-[var(--mb-navy-900)]">{value}</strong><span className="mt-1 block truncate text-[9px] text-[var(--mb-neutral-500)]">{label}</span></div>; }
function CoverageLine({ label, value, progress }: { label: string; value: string; progress: number }) { return <div><div className="flex justify-between gap-3 text-[10px]"><span className="font-semibold">{label}</span><span className="font-mono">{value}</span></div><div className="mt-2 h-1.5 bg-[var(--mb-neutral-100)]"><div className="h-full bg-[var(--mb-ocean-600)]" style={{ width: `${Math.max(4, progress)}%` }} /></div></div>; }
function formatCompact(value: number) { if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toLocaleString("fr-FR", { maximumFractionDigits: 2 })} Md FCFA`; return `${Math.round(value / 1_000_000).toLocaleString("fr-FR")} M FCFA`; }
