"use client";

import { quays, type MapAlert } from "@/data/ministryControlTowerData";
import type { FundingDossierRecord, FundingOpportunity, GeneratedArtifact } from "@/data/ministryValueJourneyData";
import type { DossierOperationnel } from "@/lib/ministryOperationalDossiers";
import { draftArbitrationNote } from "@/lib/mbambulaanAssistant";
import { DataTrustBadge, primaryButton, secondaryButton, StatusBadge, WorkspaceHeader } from "./MinistryControlTowerParts";

export function MinistryPilotageView({ dossiers, alerts, artifacts, opportunities, fundingDossiers, onViewAtlas, onOpenDossier, onOpenDossiers }: {
  dossiers: DossierOperationnel[];
  alerts: MapAlert[];
  artifacts: GeneratedArtifact[];
  opportunities: FundingOpportunity[];
  fundingDossiers: FundingDossierRecord[];
  onViewAtlas: (quayId: string) => void;
  onOpenDossier: (dossier: DossierOperationnel) => void;
  onOpenDossiers: () => void;
}) {
  const kayar = dossiers.find((dossier) => dossier.id === "VER-2026-0142") ?? dossiers[0];
  const attention = dossiers.filter((item) => item.workStatus !== "Terminé");
  const decisions = dossiers.filter((item) => item.type === "Décision institutionnelle" && item.workStatus !== "Terminé").slice(0, 3);
  const needs = dossiers.filter((item) => item.type === "Besoin filière");
  const readyToClose = dossiers.filter((item) => item.action === "close-dossier");
  const amount = opportunities.reduce((total, item) => total + item.estimatedAmount, 0);
  const beneficiaries = opportunities.reduce((total, item) => total + item.beneficiaries, 0);
  const note = kayar ? draftArbitrationNote(kayar) : null;
  const trustedQuays = quays.filter((quay) => ["verified", "consolidated"].includes(quay.trustLevel)).length;

  return <section className="min-h-full bg-[var(--mb-offwhite)]">
    <WorkspaceHeader title="Pilotage" question="Lire la situation nationale, ouvrir les dossiers prioritaires et préparer une décision documentée." scope="Nationale" onScopeChange={() => undefined} onExport={() => undefined} />
    <div className="border-b border-[var(--mb-neutral-200)] bg-[var(--mb-navy-900)] px-4 py-6 text-white sm:px-6">
      <div className="mx-auto max-w-[86rem]"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[var(--mb-ocean-400)]">Situation nationale · démonstration</p><div className="mt-3 grid gap-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><h2 className="max-w-4xl text-[24px] font-semibold leading-tight">Les informations terrain deviennent des dossiers traçables, des preuves exploitables et des décisions documentées.</h2><p className="mt-3 max-w-3xl text-[11px] leading-5 text-white/65">{attention.length} dossier(s) demandent une attention et {dossiers.filter((item) => item.workStatus === "Terminé").length} ont déjà une sortie documentée. Kayar reste la priorité de démonstration : l’écart de pesée doit être confirmé avant consolidation.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => onViewAtlas("kayar")} className="h-10 bg-[var(--mb-sand-300)] px-4 text-[11px] font-bold text-[var(--mb-navy-900)]">Voir dans l’Atlas</button>{kayar ? <button onClick={() => onOpenDossier(kayar)} className="h-10 border border-white/25 px-4 text-[11px] font-bold text-white">Ouvrir le dossier</button> : null}</div></div><p className="mt-5 border-t border-white/10 pt-3 text-[10px] text-white/50">Lecture fondée sur les postes locaux, pièces et validations humaines visibles dans les dossiers. Modèle paramétrable avec les services du Ministère après cadrage.</p></div>
    </div>
    <div className="mx-auto max-w-[86rem] px-4 py-5 sm:px-6">
      <section className="grid grid-cols-2 border border-[var(--mb-neutral-200)] bg-white md:grid-cols-3 xl:grid-cols-6"><PilotMetric label="Quais suivis" value={String(quays.length)} action="Voir l’Atlas" onClick={() => onViewAtlas("kayar")} /><PilotMetric label="Débarquements du jour" value={String(quays.reduce((sum, quay) => sum + quay.landingsToday, 0))} action="Comparer les quais" onClick={() => onViewAtlas("joal")} /><PilotMetric label="Situations en attention" value={String(alerts.length)} action="Ouvrir les dossiers" onClick={onOpenDossiers} /><PilotMetric label="Décisions attendues" value={String(decisions.length)} action="Voir les sujets" onClick={onOpenDossiers} /><PilotMetric label="Prêts à clôturer" value={String(readyToClose.length)} action="Contrôler" onClick={onOpenDossiers} /><PilotMetric label="Montant à instruire" value={`${Math.round(amount / 1_000_000)} M`} action="Voir besoins filière" onClick={onOpenDossiers} /></section>
      <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,.8fr)]">
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader title="Décisions attendues" helper="Trois sujets maximum, reliés à leur dossier et à leurs preuves." /><div className="divide-y divide-[var(--mb-neutral-100)]">{[kayar, ...decisions].filter((item, index, items): item is DossierOperationnel => Boolean(item) && items.findIndex((other) => other?.id === item?.id) === index).slice(0, 3).map((dossier) => <article key={dossier.id} className="grid gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_auto]"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] font-bold text-[var(--mb-ocean-600)]">{dossier.id}</span><StatusBadge level={dossier.workStatus === "Bloqué" ? "urgent" : "surveillance"}>{dossier.workStatus}</StatusBadge></div><h3 className="mt-2 text-[13px] font-semibold text-[var(--mb-navy-900)]">{dossier.linkedObject}</h3><p className="mt-1 text-[10px] leading-4 text-[var(--mb-neutral-600)]">{dossier.territory} · {dossier.currentOwner} · décision attendue : {dossier.nextAction}</p><div className="mt-2"><DataTrustBadge level={dossier.pieces.some((piece) => piece.status === "Attendue") ? "declared" : "verified"} source={`${dossier.pieces.filter((piece) => piece.status === "Disponible").length} pièce(s) disponible(s) dans ${dossier.id}.`} /></div></div><button onClick={() => onOpenDossier(dossier)} className={`${secondaryButton} self-center`}>Ouvrir le dossier</button></article>)}</div></section>
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader title="Couverture & confiance" helper="Fraîcheur et maturité des informations visibles, sans source serveur simulée." /><div className="grid gap-4 p-4"><CoverageLine label="Quais couverts" value={`${quays.length} / ${quays.length}`} progress={100} /><CoverageLine label="Informations vérifiées ou consolidées" value={`${trustedQuays} / ${quays.length}`} progress={trustedQuays / quays.length * 100} /><CoverageLine label="Dossiers avec pièces disponibles" value={`${dossiers.filter((item) => item.pieces.some((piece) => piece.status === "Disponible")).length} / ${dossiers.length}`} progress={dossiers.filter((item) => item.pieces.some((piece) => piece.status === "Disponible")).length / Math.max(dossiers.length, 1) * 100} /><p className="border-l-2 border-[var(--mb-ocean-400)] pl-3 text-[10px] leading-5 text-[var(--mb-neutral-600)]">Sources : postes locaux, appels, WhatsApp manuel, agents terrain, formulaires et documents de démonstration.</p></div></section>
      </div>
      <div className="mt-5 grid gap-5 xl:grid-cols-2">
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader title="Filière & financement" helper="Les besoins qualifiés deviennent des dossiers à instruire, pas un portail partenaire autonome." /><div className="grid grid-cols-2 border-b border-[var(--mb-neutral-100)] sm:grid-cols-4"><CompactFact label="Besoins filière" value={String(needs.length)} /><CompactFact label="Dossiers constitués" value={String(fundingDossiers.length)} /><CompactFact label="Bénéficiaires estimés" value={String(beneficiaries)} /><CompactFact label="Montant estimé" value={`${Math.round(amount / 1_000_000)} M FCFA`} /></div><div className="p-4"><button onClick={onOpenDossiers} className={primaryButton}>Voir les besoins filière</button></div></section>
        <section className="border border-[var(--mb-neutral-200)] bg-white"><SectionHeader title="Assistance à l’arbitrage" helper="Fonction locale déterministe · aucune API ni décision automatique." />{note ? <div className="p-4"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-[var(--mb-ocean-600)]">Proposition à valider</p><h3 className="mt-2 text-[13px] font-semibold">{note.subject}</h3><p className="mt-2 text-[10px] leading-5 text-[var(--mb-neutral-600)]">{note.recommendation}</p><p className="mt-3 text-[10px] text-[var(--mb-neutral-500)]">Sources : {note.sources.join(" · ") || "dossier local de démonstration"}</p>{kayar ? <button onClick={() => onOpenDossier(kayar)} className={`${secondaryButton} mt-3`}>Relire les sources dans le dossier</button> : null}</div> : null}</section>
      </div>
      <section className="mt-5 border border-[var(--mb-neutral-200)] bg-white"><SectionHeader title="Documents récents" helper="Trois sorties structurées : rapport de zone, note d’arbitrage et dossier de financement. La transmission externe reste manuelle." /><div className="divide-y divide-[var(--mb-neutral-100)]">{artifacts.filter((artifact) => ["export-zone", "note", "funding"].includes(artifact.kind)).slice(0, 3).map((artifact) => <article key={artifact.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div><h3 className="text-[11px] font-semibold">{artifact.title}</h3><p className="mt-1 text-[10px] text-[var(--mb-neutral-600)]">{artifact.scope} · {artifact.createdAt} · validateur : {artifact.validator}</p></div><span className="self-center text-[10px] font-bold text-[var(--mb-ocean-600)]">Document local prêt à relire</span></article>)}</div></section>
    </div>
  </section>;
}

function PilotMetric({ label, value, action, onClick }: { label: string; value: string; action: string; onClick: () => void }) { return <button onClick={onClick} className="min-w-0 border-b border-r border-[var(--mb-neutral-200)] p-3 text-left hover:bg-[var(--mb-offwhite)]"><span className="block text-[10px] font-semibold text-[var(--mb-neutral-600)]">{label}</span><strong className="mt-2 block truncate font-mono text-[22px] text-[var(--mb-navy-900)]">{value}</strong><span className="mt-2 block text-[10px] font-bold text-[var(--mb-ocean-600)]">{action} →</span></button>; }
function SectionHeader({ title, helper }: { title: string; helper: string }) { return <header className="border-b border-[var(--mb-neutral-200)] px-4 py-3"><h2 className="text-[13px] font-semibold text-[var(--mb-navy-900)]">{title}</h2><p className="mt-1 text-[10px] text-[var(--mb-neutral-600)]">{helper}</p></header>; }
function CoverageLine({ label, value, progress }: { label: string; value: string; progress: number }) { return <div><div className="flex justify-between gap-3 text-[10px]"><span className="font-semibold">{label}</span><span className="font-mono">{value}</span></div><div className="mt-2 h-1.5 bg-[var(--mb-neutral-100)]"><div className="h-full bg-[var(--mb-ocean-600)]" style={{ width: `${Math.max(4, progress)}%` }} /></div></div>; }
function CompactFact({ label, value }: { label: string; value: string }) { return <div className="border-b border-r border-[var(--mb-neutral-100)] p-3"><p className="text-[10px] text-[var(--mb-neutral-600)]">{label}</p><p className="mt-2 font-mono text-[16px] font-semibold text-[var(--mb-navy-900)]">{value}</p></div>; }
