"use client";

import { useMemo, useState } from "react";
import type { CommunityNeed, FieldReferent, SpeciesRecord } from "@/data/ministryControlTowerData";
import type { FundingOpportunity } from "@/data/ministryValueJourneyData";
import { formatFcfa } from "@/data/ministryValueJourneyData";
import { StatusBadge } from "./MinistryControlTowerParts";

export function SimulationNotice() {
  return <span className="inline-flex items-center gap-1.5 rounded-[2px] border border-[var(--mb-neutral-200)] bg-white px-2 py-1 font-mono text-[8px] font-bold uppercase tracking-[0.05em] text-[var(--mb-neutral-600)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--mb-ocean-400)]" />Données de démonstration</span>;
}

export function ReferentsPanel({ referents }: { referents: FieldReferent[] }) {
  return <section className="border-t border-[var(--mb-neutral-100)]"><header className="flex items-center justify-between gap-2 px-4 py-2.5"><div><h3 className="text-[10px] font-bold text-[var(--mb-navy-900)]">Référents mandatés</h3><p className="mt-0.5 text-[8px] text-[var(--mb-neutral-600)]">Contact via cellule régionale</p></div><span className="font-mono text-[8px] text-[var(--mb-neutral-400)]">{referents.length} ACTIF(S)</span></header>{referents.length ? <div className="divide-y divide-[var(--mb-neutral-100)] border-t border-[var(--mb-neutral-100)]">{referents.slice(0, 3).map((referent) => <article key={referent.id} className="px-4 py-2.5"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-semibold">{referent.name}</p><p className="mt-0.5 text-[8px] text-[var(--mb-neutral-600)]">{referent.role} · {referent.contactChannel}</p></div><span className="font-mono text-[9px] font-bold text-[var(--mb-green-600)]">{referent.reliabilityScore}%</span></div><div className="mt-2 flex items-center justify-between gap-2 text-[8px] text-[var(--mb-neutral-400)]"><span>{referent.verificationsCompleted} vérifications</span><span>{referent.supervisingCell}</span></div></article>)}</div> : <p className="border-t border-[var(--mb-neutral-100)] px-4 py-3 text-[9px] text-[var(--mb-neutral-600)]">Aucun référent mandaté rattaché à ce quai.</p>}</section>;
}

export function FundingInsights({ needs, opportunities }: { needs: CommunityNeed[]; opportunities: FundingOpportunity[] }) {
  const signaled = needs.length;
  const qualified = opportunities.length;
  const eligible = opportunities.filter((item) => !["À qualifier"].includes(item.status)).length;
  const funded = opportunities.filter((item) => item.status === "Financé").length;
  const total = opportunities.reduce((sum, item) => sum + item.estimatedAmount, 0);
  const fundedAmount = opportunities.filter((item) => item.status === "Financé").reduce((sum, item) => sum + item.estimatedAmount, 0);
  const categories = useMemo(() => Object.entries(opportunities.reduce<Record<string, number>>((result, item) => ({ ...result, [item.category]: (result[item.category] || 0) + item.estimatedAmount }), {})).sort((a, b) => b[1] - a[1]), [opportunities]);
  const maxCategory = Math.max(...categories.map(([, amount]) => amount), 1);
  const monthly = [{ month: "Fév.", qualified: 420, funded: 180 }, { month: "Mars", qualified: 610, funded: 240 }, { month: "Avr.", qualified: 760, funded: 340 }, { month: "Mai", qualified: 940, funded: 430 }, { month: "Juin", qualified: 1120, funded: 520 }, { month: "Juil.", qualified: 1380, funded: 640 }];
  return <section className="border-b border-[var(--mb-neutral-200)] bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><div><h2 className="text-[11px] font-bold text-[var(--mb-navy-900)]">Lecture du financement</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">Qualifier, débloquer et financer les besoins documentés.</p></div><SimulationNotice /></header><div className="grid lg:grid-cols-[1.2fr_.8fr_1fr]"><div className="border-b border-[var(--mb-neutral-200)] p-3 lg:border-b-0 lg:border-r"><p className="font-mono text-[8px] uppercase text-[var(--mb-neutral-400)]">Entonnoir de financement</p><div className="mt-3 grid grid-cols-4 gap-1">{[["Signalés", signaled], ["Qualifiés", qualified], ["Éligibles", eligible], ["Financés", funded]].map(([label, value], index) => <div key={String(label)} className="text-center"><div className="grid h-14 place-items-center bg-[var(--mb-ocean-600)] text-white" style={{ opacity: 1 - index * .18 }}><strong className="font-mono text-[16px]">{value}</strong></div><p className="mt-1 text-[8px] text-[var(--mb-neutral-600)]">{label}</p></div>)}</div><p className="mt-3 text-[9px] font-semibold text-[var(--mb-red-600)]">Reste à financer · {formatFcfa(Math.max(0, total - fundedAmount))}</p></div><div className="border-b border-[var(--mb-neutral-200)] p-3 lg:border-b-0 lg:border-r"><p className="font-mono text-[8px] uppercase text-[var(--mb-neutral-400)]">Par catégorie</p><div className="mt-3 grid gap-2">{categories.slice(0, 4).map(([category, amount]) => <div key={category}><div className="flex justify-between gap-2 text-[8px]"><span>{category}</span><span className="font-mono">{Math.round(amount / 1_000_000)} M</span></div><div className="mt-1 h-1.5 bg-[var(--mb-neutral-100)]"><div className="h-full bg-[var(--mb-ocean-600)]" style={{ width: `${Math.max(6, amount / maxCategory * 100)}%` }} /></div></div>)}</div></div><div className="p-3"><p className="font-mono text-[8px] uppercase text-[var(--mb-neutral-400)]">Montants qualifiés / financés · M FCFA</p><div className="mt-3 flex h-20 items-end gap-2">{monthly.map((item) => <div key={item.month} className="flex flex-1 items-end justify-center gap-0.5"><span title={`Qualifié ${item.qualified} M`} className="w-2 bg-[var(--mb-ocean-400)]" style={{ height: `${item.qualified / 14}%` }} /><span title={`Financé ${item.funded} M`} className="w-2 bg-[var(--mb-green-600)]" style={{ height: `${item.funded / 14}%` }} /></div>)}</div><div className="mt-1 grid grid-cols-6 gap-2 text-center font-mono text-[7px] text-[var(--mb-neutral-400)]">{monthly.map((item) => <span key={item.month}>{item.month}</span>)}</div><div className="mt-2 flex gap-3 text-[8px] text-[var(--mb-neutral-600)]"><span><i className="mr-1 inline-block h-1.5 w-1.5 bg-[var(--mb-ocean-400)]" />Qualifié</span><span><i className="mr-1 inline-block h-1.5 w-1.5 bg-[var(--mb-green-600)]" />Financé</span></div></div></div></section>;
}

export function SpeciesDirectory({ species }: { species: SpeciesRecord[] }) {
  const [filter, setFilter] = useState<"Tous" | SpeciesRecord["regulatoryStatus"]>("Tous");
  const filtered = filter === "Tous" ? species : species.filter((item) => item.regulatoryStatus === filter);
  const maxVolume = Math.max(...species.map((item) => item.recentLandingVolume), 1);
  return <section className="border border-[var(--mb-neutral-200)] bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--mb-neutral-200)] px-3 py-2.5"><div><h2 className="text-[11px] font-bold text-[var(--mb-navy-900)]">Répertoire espèces & variétés</h2><p className="mt-0.5 text-[9px] text-[var(--mb-neutral-600)]">Volumes, saisons et espèces sensibles pour éclairer réglementation, biodiversité et financement.</p></div><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)} className="h-8 rounded-[3px] border border-[var(--mb-neutral-200)] bg-white px-2 text-[9px] font-semibold"><option>Tous</option><option>Libre</option><option>Réglementée</option><option>Protégée</option><option>Repos biologique</option></select></header><div className="grid sm:grid-cols-2 xl:grid-cols-4">{filtered.map((item) => <article key={item.id} className="border-b border-r border-[var(--mb-neutral-100)] p-3"><div className="flex items-start justify-between gap-2"><div><h3 className="text-[10px] font-semibold">{item.localName}</h3><p className="mt-0.5 text-[8px] italic text-[var(--mb-neutral-400)]">{item.scientificName}</p></div><StatusBadge level={item.alertLevel}>{item.regulatoryStatus}</StatusBadge></div><p className="mt-3 font-mono text-[14px] font-bold text-[var(--mb-navy-900)]">{item.recentLandingVolume.toFixed(1)} t</p><div className="mt-1 h-1.5 bg-[var(--mb-neutral-100)]"><div className="h-full bg-[var(--mb-ocean-600)]" style={{ width: `${item.recentLandingVolume / maxVolume * 100}%` }} /></div><p className="mt-2 text-[8px] text-[var(--mb-neutral-600)]">{item.commonZones.join(" · ")} · {item.seasonality}</p><p className="mt-2 border-l-2 border-[var(--mb-amber-500)] pl-2 text-[8px] leading-3 text-[var(--mb-neutral-600)]">{item.decisionUse}</p></article>)}</div></section>;
}
