"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ministryRegionalQuays, ministryRegions, type MinistryRegionName, type MinistryRegionalQuay } from "@/data/ministryRegionalSpace";

const capsList = ["Synthèse", "Alertes", "Notes", "Recherche assistée"] as const;
const hints = {
  centre: "Synthèse courte pour savoir quoi regarder maintenant.",
  region: "En mode région, seuls les quais de la région sélectionnée apparaissent.",
  score: "Simulation d’aide à la priorisation. Elle guide l’attention, sans décider à la place de l’humain.",
  volume: "Volumes de débarquement déclarés pour la journée, par quai ou par région.",
  alertes: "Tensions, plaintes et incidents remontés par les relais ou acteurs terrain.",
  pieces: "Justificatifs, comptes rendus, confirmations référents et pièces pouvant documenter une décision.",
  note: "Prépare une note de travail. Elle reste un brouillon tant qu’un utilisateur ne la valide pas.",
  ia: "IA simulée sur données mockées. L’humain valide chaque décision.",
  veille: "Signaux mockés de contexte filière. Aucune vraie actualité ni API externe.",
  referents: "Points d’ancrage terrain mobilisables pour vérifier, coordonner ou documenter une action."
};
const veille = [
  ["Chaîne froid à surveiller sur les quais à fort volume", "Ressources", "Tout", "attention", "Synthèse mockée Mbàmbulaan"],
  ["Signal de tension sur les débarquements urbains", "Tension terrain", "Dakar", "attention", "Relais terrain mock"],
  ["Volumes saisonniers à documenter sur Guet Ndar", "Production", "Saint-Louis", "info", "Point régional mock"],
  ["Espèce à surveiller sur Petite-Côte", "Espèces à surveiller", "Thiès", "critique", "Signal qualité mock"],
  ["Besoin de pièces programme pour froid mobile", "Programme public", "Fatick", "attention", "Programme mock"],
  ["Hygiène et qualité à vérifier sur flux crevette", "Hygiène et qualité", "Ziguinchor", "attention", "Contrôle mock"],
  ["Météo maritime simulée : lecture prudente des sorties", "Météo maritime mockée", "Louga", "info", "Scénario mock"],
  ["Signal marché sur flux fluvial", "Marché", "Kaolack", "info", "Veille mock"]
] as const;

const fmt = (r: MinistryRegionName) => r === "Tout" ? "Toutes les régions" : r;
const total = (q: MinistryRegionalQuay[], k: "tonnage" | "landings" | "incidents" | "conflicts" | "proofs") => q.reduce((s, x) => s + x[k], 0);
const dot = (t: string) => t === "Critique" ? "bg-rose-500" : t === "Forte" ? "bg-amber-400" : t === "Moyenne" ? "bg-yellow-300" : "bg-emerald-400";
const badge = (t: string) => t === "Critique" ? "bg-rose-100 text-rose-950 ring-rose-200" : t === "Forte" ? "bg-amber-100 text-amber-950 ring-amber-200" : t === "Moyenne" ? "bg-yellow-100 text-yellow-950 ring-yellow-200" : "bg-emerald-100 text-emerald-950 ring-emerald-200";

export function MinistryInstitutionalSpace() {
  const [region, setRegion] = useState<MinistryRegionName>("Tout");
  const [quayId, setQuayId] = useState("th-joal");
  const [ai, setAi] = useState(true);
  const [caps, setCaps] = useState(Object.fromEntries(capsList.map((c) => [c, c !== "Recherche assistée"])) as Record<(typeof capsList)[number], boolean>);
  const [trace, setTrace] = useState<string[]>(["Session ouverte : vision nationale multi-régions."]);
  const [status, setStatus] = useState<Record<string, string>>({});
  const [note, setNote] = useState("Aucune note préparée.");
  const [noteStatus, setNoteStatus] = useState("Aucune note ouverte");
  const [message, setMessage] = useState("IA simulée - données mockées. L'humain valide chaque décision.");
  const [focus, setFocus] = useState("");
  const [compare, setCompare] = useState("");

  const quays = useMemo(() => ministryRegionalQuays.filter((q) => region === "Tout" || q.region === region), [region]);
  const active = quays.find((q) => q.id === quayId) ?? quays[0] ?? ministryRegionalQuays[0];
  const top = [...quays].sort((a, b) => b.priorityScore - a.priorityScore).slice(0, 5);
  const volumes = [...quays].sort((a, b) => b.tonnage - a.tonnage).slice(0, 6);
  const alerts = quays.filter((q) => q.incidents + q.conflicts > 0).sort((a, b) => b.incidents + b.conflicts - (a.incidents + a.conflicts));
  const species = quays.flatMap((q) => q.sensitiveSpecies.filter((s) => s !== "Aucune alerte").map((s) => ({ q, s })));
  const watch = veille.filter((v) => v[2] === "Tout" || region === "Tout" || v[2] === region);
  const max = Math.max(...volumes.map((q) => q.tonnage), 1);

  function log(text: string) { setTrace((x) => [text, ...x].slice(0, 8)); }
  function act(id: string, label: string, text: string) {
    setStatus((x) => ({ ...x, [id]: label }));
    log(text);
    setMessage(`${text}. Simulation MVP - action non connectée au backend.`);
  }
  function chooseRegion(next: MinistryRegionName) {
    const first = ministryRegionalQuays.find((q) => next === "Tout" || q.region === next);
    setRegion(next); setQuayId(first?.id ?? ministryRegionalQuays[0].id); setFocus(""); setCompare(""); log(`Filtre appliqué : ${fmt(next)}.`);
  }
  function prepare(q = active, title = "Brouillon d’arbitrage") {
    const mode = ai && caps.Notes ? "Brouillon assisté" : "Brouillon manuel";
    setNote(`${mode} - ${title}\nContexte : ${q.name} (${q.region}) · ${q.tonnage} t · ${q.landings} débarquement(s).\nProblème observé : tension ${q.tension}, ${q.incidents} incident(s), ${q.conflicts} plainte(s), justificatif ${q.proofLevel}.\nDonnées utiles : ${q.mainSpecies.join(", ")} · financement ${q.pendingFunding} · ressources ${q.resources.join(", ")}.\nRéférent à mobiliser : ${q.referents[0]}.\nJustificatifs manquants : compte rendu terrain, confirmation référent, pièce programme ou relevé tonnage.\nProchaine action : ${q.recommendedAction}\nStatut : Brouillon à valider.`);
    setNoteStatus("Brouillon à valider"); act(`note-${q.id}`, "Brouillon à valider", `Note d’arbitrage préparée pour ${q.name}`);
  }
  function noteFlow(a: string) {
    const label = a === "Valider le brouillon" ? "Brouillon validé par utilisateur" : a === "Complément terrain" ? "Complément terrain demandé" : a === "Affecter référent" ? `Affecté à ${active.referents[0]}` : "Export de note simulé";
    setNoteStatus(label); act(`note-${a}-${active.id}`, label, `${label} · ${active.name}`);
  }
  function suggestion(kind: "note" | "verify" | "compare" | "complaints") {
    if (kind === "note") return prepare(active);
    if (kind === "verify") { setFocus("species"); return act(`verify-${active.id}`, "Vérification demandée", `Vérification terrain demandée sur ${active.name}`); }
    if (kind === "compare") { const a = volumes[0], b = volumes[1] ?? active; setCompare(`${a.name} (${a.tonnage} t) concentre plus de volume que ${b.name} (${b.tonnage} t). Lecture utile pour éviter une moyenne nationale réductrice.`); return log(`Comparaison affichée : ${a.name} / ${b.name}.`); }
    setFocus("complaints"); act(`complaints-${active.id}`, "Plaintes ouvertes", `Focus plaintes et conflits activé pour ${active.name}`);
  }

  const aiText = ai && caps.Synthèse ? `${fmt(region)} : ${quays.length} quai(s), ${total(quays, "tonnage").toFixed(1)} t, ${alerts.length} quai(s) avec alerte. Priorité : ${top[0]?.name ?? active.name}.` : "Mode manuel : lire, filtrer, agir, préparer une note et tracer restent disponibles sans assistance IA.";
  const lookNow = top[0] ? `${top[0].name} : ${top[0].tension.toLowerCase()}, ${top[0].incidents + top[0].conflicts} alerte(s), ${top[0].pendingFunding} à suivre.` : "Aucun quai prioritaire dans la sélection.";

  return (
    <main className="min-h-screen bg-[linear-gradient(180deg,#eafbf8_0%,#f7fcfb_45%,#fff8eb_100%)] text-slate-950">
      <header className="border-b border-cyan-100 bg-white/95 px-5 py-6 sm:px-8">
        <div className="mx-auto flex max-w-[96rem] flex-col gap-5 xl:flex-row xl:items-center xl:justify-between">
          <div className="flex items-center gap-4"><Link href="/" className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-700 text-sm font-black text-white">Mb</Link><div><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700">Ministère des Pêches · espace privé</p><h1 className="text-2xl font-black tracking-tight">Espace institutionnel de lecture régionale</h1></div></div>
          <div className="flex flex-wrap gap-2"><button onClick={() => prepare(active, "Point de coordination")} className="rounded-full bg-cyan-700 px-4 py-2 text-sm font-black text-white">Préparer le point de coordination</button><button onClick={() => act(`export-${region}`, "Synthèse exportée", `Synthèse exportée : ${fmt(region)}`)} className="rounded-full border border-cyan-200 bg-white px-4 py-2 text-sm font-black text-cyan-950">Exporter la synthèse</button></div>
        </div>
      </header>
      <section className="mx-auto grid max-w-[96rem] gap-10 px-5 py-8 sm:px-8">
        <Band n="01" l="Centre de pilotage national" t={`Synthèse exécutive · ${fmt(region)}`} s="Une lecture courte pour savoir quoi regarder maintenant.">
          <div className="rounded-[2rem] bg-gradient-to-br from-cyan-950 via-teal-900 to-emerald-800 p-6 text-white shadow-xl">
            <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex gap-2"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-100/70">Lecture active · {region === "Tout" ? "vision nationale multi-régions" : `région ${region}`}</p><Hint text={hints.centre} /></div><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Ce qu’il faut regarder maintenant</h2><p className="mt-4 text-sm font-bold text-cyan-50/80">{lookNow}</p></div><p className="rounded-2xl bg-white/10 p-4 text-sm font-bold ring-1 ring-white/10">Dernier point de coordination : {trace[0]}</p></div>
            <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
              <Metric l="Quais visibles" v={String(quays.length)} h={hints.region} /><Metric l="Tonnage du jour" v={`${total(quays, "tonnage").toFixed(1)} t`} h={hints.volume} /><Metric l="Débarquements" v={String(total(quays, "landings"))} h="Nombre de débarquements déclarés dans le périmètre actif." /><Metric l="Alertes ouvertes" v={String(total(quays, "incidents"))} h={hints.alertes} /><Metric l="Plaintes / conflits" v={String(total(quays, "conflicts"))} h="Points pouvant demander un arbitrage humain." /><Metric l="Actions en attente" v={String(Object.keys(status).length)} h="Actions ouvertes à suivre." /><Metric l="Justificatifs à vérifier" v={String(total(quays, "proofs"))} h={hints.pieces} /><Metric l="Note active" v={noteStatus} h={hints.note} small />
            </div>
          </div>
          <div className="grid gap-4 xl:grid-cols-[1fr_0.9fr]"><Panel t="Quais à regarder en priorité" s="Classement sans moyenne réductrice" h={hints.score}>{top.map((q) => <QuayLine key={q.id} q={q} on={() => setQuayId(q.id)} />)}</Panel><Panel t={`Quai actif : ${active.name}`} s={`${active.region} · ${active.commune}`} h="Fiche courte pour décider l’action suivante."><Row l="Niveau de vigilance" v={active.tension} /><Row l="Urgence opérationnelle" v={`${active.priorityScore}/100 · simulation`} /><Row l="Pêches du jour" v={`${active.tonnage} t · ${active.landings} débarquements`} /><Row l="Action recommandée" v={active.recommendedAction} /><Actions p="Prioriser ce quai" s={["Vérifier terrain", "Préparer note"]} on={(a) => a.includes("note") ? prepare(active) : act(`${a}-${active.id}`, a, `${a} : ${active.name}`)} /></Panel></div>
        </Band>

        <Band n="02" l="Lecture territoriale" t="Filtrer par région, puis choisir un quai" s="Un seul filtre principal pilote toute l’expérience : Région / Tout.">
          <div className="grid gap-3 md:grid-cols-4 xl:grid-cols-8">{ministryRegions.map((r) => <button key={r} onClick={() => chooseRegion(r)} className={`rounded-[1.35rem] border p-4 text-left ${region === r ? "border-cyan-600 bg-gradient-to-br from-cyan-700 to-teal-600 text-white shadow-lg" : "border-cyan-100 bg-white/80 text-cyan-950"}`}><span className="block text-lg font-black">{fmt(r)}</span><span className="mt-2 block text-xs font-black uppercase">{r === "Tout" ? ministryRegionalQuays.length : ministryRegionalQuays.filter((q) => q.region === r).length} quai(s)</span></button>)}</div>
          <Panel t="Quai de travail" s="Sélection dans le périmètre actif" h="Choisir un quai ne change pas le périmètre régional."><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><p className="text-sm font-semibold text-slate-600"><span className="block text-lg font-black text-slate-950">{active.name}</span>{active.region} · {active.commune} · {active.lat}, {active.lng}</p><select value={active.id} onChange={(e) => setQuayId(e.target.value)} className="rounded-full border border-cyan-200 bg-white px-4 py-2 text-sm font-black text-cyan-950">{quays.map((q) => <option key={q.id} value={q.id}>{q.name}</option>)}</select></div></Panel>
        </Band>

        <Band n="03" l="Indicateurs critiques" t="Priorité d’attention par quai" s="Les jauges expliquent les facteurs d’urgence opérationnelle."><div className="grid gap-3 lg:grid-cols-3"><Gauge l="Priorité d’attention" v={active.priorityScore} h={hints.score} f={["alertes ouvertes", "volume inhabituel", "justificatif manquant", "ressource critique"]} /><Gauge l="Exécution budget" v={active.budgetExecution} h="Dossiers où une justification ou un arbitrage peut être demandé." f={["budget engagé", "pièces programme", "retard dossier", "arbitrage possible"]} /><Spark quays={volumes} max={max} /></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{top.slice(0, 4).map((q) => <KpiCard key={q.id} q={q} on={() => setQuayId(q.id)} />)}</div></Band>

        <Band n="04" l="Carte et fiches de quai" t="Points de géolocalisation simulés" s="Tout affiche tous les points, une région affiche seulement ses quais."><div className="grid gap-4 xl:grid-cols-[1fr_23rem]"><Panel t="Carte stylisée des quais" s={`${quays.length} point(s) affiché(s)`} h="Coordonnées mockées, sans API externe."><div className="relative min-h-[32rem] overflow-hidden rounded-[1.5rem] bg-[radial-gradient(circle_at_18%_18%,rgba(20,184,166,0.22),transparent_30%),linear-gradient(140deg,#f8fafc,#dff7f4_46%,#f7e7c3)]"><div className="absolute left-[25%] top-8 h-[86%] w-10 rounded-full border-l-4 border-cyan-300/70" />{quays.map((q) => <button key={q.id} onClick={() => setQuayId(q.id)} className={`absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white shadow-lg ${active.id === q.id ? "h-11 w-11 ring-4 ring-cyan-900/20" : "h-7 w-7"} ${dot(q.tension)}`} style={{ left: `${q.x}%`, top: `${q.y}%` }} />)}{quays.map((q) => <span key={`${q.id}-l`} className="absolute -translate-x-1/2 rounded-full bg-white/90 px-2.5 py-1 text-[0.65rem] font-black text-slate-700" style={{ left: `${q.x}%`, top: `calc(${q.y}% + 1.35rem)` }}>{q.name}</span>)}</div></Panel><Panel t={`Fiche ${active.name}`} s={`${active.lat}, ${active.lng}`} h="Fiche opérationnelle du quai actif."><Row l="Région" v={active.region} /><Row l="Commune" v={active.commune} /><Row l="Tension" v={active.tension} /><Row l="Financement" v={active.pendingFunding} /><Row l="Ressources" v={active.resources.join(", ")} /><Actions p="Demander arbitrage" s={["Compte rendu", "Trace"]} on={(a) => a === "Demander arbitrage" ? prepare(active) : act(`${a}-${active.id}`, "Demandé", `${a} demandé : ${active.name}`)} /></Panel></div></Band>

        <Band n="05" l="Pêches du jour" t="Tonnages et variétés par quai" s="Les volumes respectent strictement le filtre régional."><Panel t="Distribution des pêches" s={fmt(region)} h={hints.volume}><Bars quays={volumes} max={max} /><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{volumes.map((q) => <Seafood key={q.id} q={q} on={() => act(`tonnage-${q.id}`, "Relevé demandé", `Relevé tonnage demandé : ${q.name}`)} />)}</div></Panel></Band>

        <Band n="06" l="Programmes et moyens" t="Budgets, ressources et programmes régionaux" s="Chaque ligne appartient au périmètre filtré."><div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><Panel t="Budgets à suivre" s="Par quai" h="Dossiers où une justification ou une pièce peut être demandée."><Table h={["Quai", "Programme", "Exécution", "Financement", "Action"]} r={top.map((q) => [q.name, `${q.programs} programme(s)`, `${q.budgetExecution}%`, q.pendingFunding, <button key={q.id} onClick={() => prepare(q)} className="btn">Arbitrage</button>])} /></Panel><Panel t="Ressources et infrastructures" s="Disponibilité simulée" h="Moyens humains, matériels et infrastructures liés aux quais visibles."><Table h={["Quai", "Ressources", "Statut", "Action"]} r={quays.slice(0, 7).map((q) => [q.name, q.resources.join(", "), status[`resource-${q.id}`] ?? "À suivre", <button key={q.id} onClick={() => act(`resource-${q.id}`, "Maintenance demandée", `Maintenance demandée : ${q.name}`)} className="btn">Maintenance</button>])} /></Panel></div></Band>

        <Band n="07" l="Alertes terrain et incidents opérationnels" t="Espèces à surveiller, conflits et plaintes" s="Signaux prudents : données mockées et vérification requise."><div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><Panel t="Espèces à surveiller" s="Signaux à vérifier" h="Signal à vérifier avant décision. Données mockées.">{(species.length ? species : quays.slice(0, 2).map((q) => ({ q, s: "Aucune alerte" }))).slice(0, 6).map(({ q, s }) => <Signal key={`${q.id}-${s}`} q={q} s={s} focus={focus === "species"} on={(a) => a === "Créer note" ? prepare(q, `Note de vigilance ${s}`) : act(`${a}-${q.id}-${s}`, a, `${a} : ${s} · ${q.name}`)} />)}</Panel><Panel t="Conflits et plaintes" s="Déclarations terrain" h="Plaintes et conflits demandant vérification, affectation ou arbitrage."><div className={focus === "complaints" ? "rounded-3xl bg-rose-50 p-3 ring-2 ring-rose-300" : ""}><Table h={["Quai", "Plaintes", "Incidents", "Statut", "Action"]} r={alerts.slice(0, 7).map((q) => [q.name, String(q.conflicts), String(q.incidents), status[`complaint-${q.id}`] ?? q.tension, <button key={q.id} onClick={() => act(`complaint-${q.id}`, "À arbitrer", `Plainte ouverte pour arbitrage : ${q.name}`)} className="btn">Arbitrer</button>])} /></div></Panel></div></Band>

        <Band n="08" l="Coordination terrain" t="Référents et actions suivies" s="Les référents sont des points d’ancrage terrain, pas des contacts CRM."><div className="grid gap-4 xl:grid-cols-[1fr_0.72fr]"><Panel t="Référents par quai" s={fmt(region)} h={hints.referents}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{quays.slice(0, 9).map((q) => <Referent key={q.id} q={q} status={status[`report-${q.id}`] ?? "Disponible"} on={() => act(`report-${q.id}`, "Compte rendu demandé", `Compte rendu demandé : ${q.name}`)} />)}</div></Panel><Panel t="Actions en attente" s="Traces visibles" h="Actions ouvertes à suivre, valider ou affecter."><div className="grid gap-2">{trace.map((x, i) => <p key={`${x}-${i}`} className="rounded-2xl border border-cyan-100 bg-gradient-to-br from-cyan-50 to-emerald-50 p-3 text-sm font-bold text-slate-700">{x}</p>)}</div><p className="mt-4 rounded-2xl bg-amber-50 p-3 text-xs font-black text-amber-950">{message}</p></Panel></div></Band>

        <Band n="09" l="Justificatifs, notes et traces" t="Décision documentée" s="Les pièces de suivi et brouillons suivent le périmètre régional ou le quai actif."><div className="grid gap-5 lg:grid-cols-[1fr_0.85fr]"><Panel t="Justificatifs et traces" s={fmt(region)} h={hints.pieces}><Table h={["Quai", "Niveau", "Pièces", "Trace utile"]} r={quays.slice(0, 8).map((q) => [q.name, q.proofLevel, String(q.proofs), q.recommendedAction])} /></Panel><Panel t="Note d’arbitrage" s={noteStatus} h={hints.note}><p className="whitespace-pre-line rounded-2xl bg-cyan-50 p-3 text-sm font-bold leading-6 text-cyan-950">{note}</p><Actions p="Valider le brouillon" s={["Complément terrain", "Affecter référent", "Exporter note"]} on={noteFlow} />{compare && <p className="mt-3 rounded-2xl bg-amber-50 p-3 text-sm font-bold text-amber-950">{compare}</p>}</Panel></div></Band>

        <Band n="10" l="Veille filière et signaux du moment" t="Contexte filière mocké, compact et actionnable" s="La veille respecte le filtre Région / Tout et ne s’appuie sur aucune actualité réelle."><Panel t="Signaux à relier à la synthèse" s={fmt(region)} h={hints.veille}><div className="grid gap-3 lg:grid-cols-2">{watch.map((v) => <Watch key={`${v[2]}-${v[0]}`} v={v} ai={ai} on={(a) => { if (a === "Inclure note") { setNote(`Brouillon veille - ${v[0]}\nCatégorie : ${v[1]}\nPortée : ${v[2] === "Tout" ? "national" : v[2]}\nSource : ${v[4]}\nAction proposée : relier ce signal à la synthèse ${fmt(region)}.\nStatut : Brouillon à valider.`); setNoteStatus("Brouillon veille à valider"); } act(`watch-${v[2]}-${v[0]}-${a}`, "Veille ajoutée", `Veille filière : ${v[0]} · ${a}`); }} />)}</div></Panel></Band>

        <Band n="11" l="IA Mbàmbulaan gouvernée" t="IA actionnable, jamais décisionnaire" s="Chaque suggestion propose un choix utilisateur et produit un brouillon, une trace ou un focus."><div className="grid gap-5 lg:grid-cols-[0.82fr_1.18fr]"><Panel t="Gouvernance IA" s="Activable, contrôlée, simulée" h={hints.ia}><button onClick={() => setAi((x) => !x)} className={`flex w-full items-center justify-between rounded-2xl p-3 text-left ${ai ? "bg-emerald-50 text-emerald-950" : "bg-slate-100 text-slate-600"}`}><span><span className="block text-sm font-black">Activer IA Mbàmbulaan</span><span className="block text-xs font-semibold">{ai ? "Enrichit synthèses, alertes et notes." : "Mode manuel complet."}</span></span><span className="rounded-full bg-white px-3 py-1 text-xs font-black">{ai ? "Activée" : "Désactivée"}</span></button><div className="mt-3 grid gap-2">{capsList.map((c) => <label key={c} className={`flex items-center justify-between rounded-2xl border p-3 text-sm font-black ${ai ? "border-cyan-100 bg-white" : "border-slate-100 bg-slate-50 text-slate-400"}`}><span>{c}</span><input type="checkbox" checked={caps[c]} disabled={!ai} onChange={() => setCaps((x) => ({ ...x, [c]: !x[c] }))} className="h-4 w-4 accent-cyan-700" /></label>)}</div></Panel><Panel t="Suggestions IA actionnables" s="Simulation MVP" h="L’utilisateur choisit ou ignore chaque proposition."><p className="rounded-2xl bg-cyan-50 p-3 text-sm font-bold text-cyan-950">{aiText}</p>{ai ? <div className="mt-4 grid gap-3 md:grid-cols-2">{caps.Notes && <Suggest t={`Préparer une note sur ${active.name}`} a={["Créer brouillon", "Ignorer"]} on={(a) => a === "Créer brouillon" ? suggestion("note") : log(`Suggestion ignorée : note ${active.name}.`)} />}{caps.Alertes && <Suggest t={`Vérifier une espèce sensible à ${active.name}`} a={["Demander vérification", "Ignorer"]} on={(a) => a === "Demander vérification" ? suggestion("verify") : log(`Suggestion ignorée : vérification ${active.name}.`)} />}{caps.Synthèse && <Suggest t="Comparer les volumes des quais affichés" a={["Comparer", "Ignorer"]} on={(a) => a === "Comparer" ? suggestion("compare") : log("Suggestion ignorée : comparaison volumes.")} />}{caps["Recherche assistée"] && <Suggest t={`Ouvrir les plaintes de ${active.region}`} a={["Ouvrir plaintes", "Ignorer"]} on={(a) => a === "Ouvrir plaintes" ? suggestion("complaints") : log(`Suggestion ignorée : plaintes ${active.region}.`)} />}</div> : <p className="mt-4 rounded-2xl bg-slate-100 p-3 text-sm font-black text-slate-600">Mode manuel : lire, filtrer, agir, préparer une note et tracer restent disponibles.</p>}<p className="mt-4 rounded-2xl bg-amber-50 p-3 text-xs font-black text-amber-950">IA simulée - données mockées. L'humain valide chaque décision.</p></Panel></div></Band>
      </section>
    </main>
  );
}

function Band({ n, l, t, s, children }: { n: string; l: string; t: string; s: string; children: React.ReactNode }) { return <section className="grid gap-5 rounded-[2.35rem] border border-cyan-100/80 bg-white/70 p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-700">{n} · {l}</p><h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{t}</h2></div><p className="max-w-2xl text-sm font-semibold leading-6 text-slate-600">{s}</p></div>{children}</section>; }
function Panel({ t, s, h, children }: { t: string; s: string; h?: string; children: React.ReactNode }) { return <section className="rounded-[1.75rem] border border-cyan-100 bg-white/95 p-5 shadow-sm"><div className="mb-5 flex justify-between gap-3"><div><h3 className="text-lg font-black">{t}</h3><p className="mt-1 text-xs font-bold uppercase tracking-[0.12em] text-cyan-700/70">{s}</p></div>{h && <Hint text={h} />}</div>{children}</section>; }
function Hint({ text }: { text: string }) { return <span className="group relative inline-flex"><span className="grid h-5 w-5 place-items-center rounded-full bg-cyan-50 text-[0.7rem] font-black text-cyan-800 ring-1 ring-cyan-200">i</span><span className="pointer-events-none absolute right-0 top-7 z-10 hidden w-64 rounded-2xl bg-cyan-950 p-3 text-xs font-semibold leading-5 text-white shadow-xl group-hover:block">{text}</span></span>; }
function Metric({ l, v, h, small }: { l: string; v: string; h: string; small?: boolean }) { return <div className="rounded-2xl bg-white/10 p-4 ring-1 ring-white/10"><div className="flex justify-between gap-2"><p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-cyan-100/75">{l}</p><Hint text={h} /></div><p className={`${small ? "text-sm leading-5" : "text-2xl"} mt-2 font-black text-white`}>{v}</p></div>; }
function QuayLine({ q, on }: { q: MinistryRegionalQuay; on: () => void }) { return <button onClick={on} className="grid gap-2 rounded-2xl bg-gradient-to-r from-cyan-50 to-emerald-50 p-3 text-left"><span className="flex justify-between text-sm font-black"><span>{q.name}</span><span>{q.priorityScore}/100</span></span><span className="h-2 rounded-full bg-white"><span className={`block h-full rounded-full ${dot(q.tension)}`} style={{ width: `${q.priorityScore}%` }} /></span></button>; }
function KpiCard({ q, on }: { q: MinistryRegionalQuay; on: () => void }) { return <button onClick={on} className="rounded-[1.25rem] border border-cyan-100 bg-gradient-to-br from-white to-cyan-50 p-4 text-left shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-lg font-black">{q.name}</p><p className="text-xs font-bold text-slate-500">{q.region}</p></div><span className={`rounded-full px-3 py-1 text-[0.65rem] font-black ring-1 ${badge(q.tension)}`}>{q.tension}</span></div><p className="mt-4 text-3xl font-black text-cyan-950">{q.priorityScore}</p><p className="text-xs font-bold text-slate-500">urgence opérationnelle · {q.tonnage} t · {q.incidents + q.conflicts} alerte(s)</p></button>; }
function Gauge({ l, v, h, f }: { l: string; v: number; h: string; f: string[] }) { const tone = v >= 80 ? "from-rose-500 to-orange-400" : v >= 65 ? "from-amber-400 to-yellow-300" : "from-emerald-400 to-teal-400"; return <div className="rounded-[1.35rem] border border-cyan-100 bg-gradient-to-br from-cyan-50 via-white to-emerald-50 p-4"><div className="flex justify-between"><p className="text-xs font-black uppercase tracking-[0.14em] text-cyan-700">{l}</p><Hint text={h} /></div><div className="mt-4 flex items-end justify-between"><p className="text-4xl font-black">{v}</p><span className="rounded-full bg-white px-3 py-1 text-xs font-black ring-1 ring-cyan-100">simulation</span></div><div className="mt-3 h-3 rounded-full bg-white ring-1 ring-cyan-100"><div className={`h-full rounded-full bg-gradient-to-r ${tone}`} style={{ width: `${v}%` }} /></div><div className="mt-3 flex flex-wrap gap-2">{f.map((x) => <span key={x} className="rounded-full bg-white px-3 py-1 text-[0.68rem] font-black text-slate-600 ring-1 ring-cyan-100">{x}</span>)}</div></div>; }
function Spark({ quays, max }: { quays: MinistryRegionalQuay[]; max: number }) { return <Panel t="Volume par quai" s="mini bar chart" h={hints.volume}><div className="flex h-24 items-end gap-2">{quays.map((q) => <div key={q.id} className="flex flex-1 flex-col items-center gap-2"><span className="w-full rounded-t bg-gradient-to-t from-cyan-700 to-teal-400" style={{ height: `${22 + (q.tonnage / max) * 70}%` }} /><span className="max-w-16 truncate text-[0.62rem] font-black text-slate-500">{q.name}</span></div>)}</div></Panel>; }
function Bars({ quays, max }: { quays: MinistryRegionalQuay[]; max: number }) { return <div className="grid gap-3">{quays.map((q) => <div key={q.id} className="grid gap-2"><div className="flex justify-between text-sm font-black"><span>{q.name}</span><span>{q.tonnage} t</span></div><div className="h-3 rounded-full bg-cyan-50"><div className="h-full rounded-full bg-gradient-to-r from-cyan-600 to-emerald-400" style={{ width: `${Math.max(12, (q.tonnage / max) * 100)}%` }} /></div></div>)}</div>; }
function Seafood({ q, on }: { q: MinistryRegionalQuay; on: () => void }) { return <article className="rounded-2xl border border-cyan-100 bg-gradient-to-br from-white to-emerald-50 p-4"><div className="flex justify-between gap-3"><div><p className="font-black">{q.name}</p><p className="text-xs font-bold text-slate-500">{q.landings} débarquements · {q.sevenDayVariation}</p></div><span className={`rounded-full px-3 py-1 text-[0.65rem] font-black ring-1 ${badge(q.tension)}`}>{q.tension}</span></div><p className="mt-3 text-2xl font-black text-cyan-950">{q.tonnage} t</p><p className="mt-2 text-xs font-semibold text-slate-600">{q.mainSpecies.join(", ")}</p><button onClick={on} className="btn mt-4">Demander relevé</button></article>; }
function Signal({ q, s, focus, on }: { q: MinistryRegionalQuay; s: string; focus: boolean; on: (a: string) => void }) { return <div className={`rounded-2xl border border-amber-100 bg-gradient-to-br from-white via-amber-50 to-cyan-50 p-4 ${focus ? "ring-2 ring-amber-300" : ""}`}><div className="flex justify-between gap-3"><div><p className="font-black">{s}</p><p className="text-xs font-bold text-slate-500">{q.name} · {q.region}</p></div><span className={`rounded-full px-3 py-1 text-[0.65rem] font-black ring-1 ${badge(q.tension)}`}>{q.tension}</span></div><p className="mt-3 text-sm font-semibold text-slate-600">Signal à vérifier · données mockées · vérification humaine requise.</p><div className="mt-4 flex flex-wrap gap-2">{["Vérifier", "Créer note", "Ajouter trace"].map((a) => <button key={a} onClick={() => on(a)} className="btn">{a}</button>)}</div></div>; }
function Referent({ q, status, on }: { q: MinistryRegionalQuay; status: string; on: () => void }) { return <div className="rounded-2xl border border-cyan-100 bg-gradient-to-br from-cyan-50 via-white to-emerald-50 p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-black">{q.referents[0]}</p><p className="text-xs font-semibold text-slate-500">{q.name} · {q.region}</p></div><span className="rounded-full bg-white px-2 py-1 text-[0.65rem] font-black text-cyan-900">{status}</span></div><p className="mt-2 text-xs font-bold text-slate-600">{q.recommendedAction}</p><button onClick={on} className="btn mt-3">Compte rendu</button></div>; }
function Table({ h, r }: { h: string[]; r: React.ReactNode[][] }) { return <div className="overflow-x-auto rounded-2xl border border-cyan-100"><table className="w-full min-w-[44rem] text-left text-sm"><thead className="bg-cyan-50 text-xs uppercase tracking-[0.12em] text-cyan-900"><tr>{h.map((x) => <th key={x} className="p-3 font-black">{x}</th>)}</tr></thead><tbody className="divide-y divide-cyan-50 bg-white">{r.map((row, i) => <tr key={i}>{row.map((c, j) => <td key={j} className="p-3 font-semibold text-slate-700">{c}</td>)}</tr>)}</tbody></table></div>; }
function Actions({ p, s, on }: { p: string; s: string[]; on: (a: string) => void }) { return <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => on(p)} className="rounded-full bg-gradient-to-r from-cyan-700 to-teal-600 px-4 py-2 text-sm font-black text-white">{p}</button>{s.map((x) => <button key={x} onClick={() => on(x)} className="rounded-full border border-cyan-200 bg-cyan-50 px-4 py-2 text-sm font-black text-cyan-950">{x}</button>)}</div>; }
function Row({ l, v }: { l: string; v: string }) { return <div className="flex justify-between gap-4 border-b border-cyan-50 py-2 text-sm font-bold"><span className="text-slate-500">{l}</span><span className="text-right">{v}</span></div>; }
function Watch({ v, ai, on }: { v: (typeof veille)[number]; ai: boolean; on: (a: string) => void }) { const tone = v[3] === "critique" ? "bg-rose-100 text-rose-950 ring-rose-200" : v[3] === "attention" ? "bg-amber-100 text-amber-950 ring-amber-200" : "bg-cyan-100 text-cyan-950 ring-cyan-200"; return <article className="rounded-2xl border border-cyan-100 bg-gradient-to-br from-white via-cyan-50 to-emerald-50 p-4"><div className="flex justify-between gap-3"><div><p className="text-sm font-black">{v[0]}</p><p className="text-xs font-bold text-slate-500">{v[1]} · {v[2] === "Tout" ? "national" : v[2]}</p></div><span className={`rounded-full px-3 py-1 text-[0.65rem] font-black ring-1 ${tone}`}>{v[3]}</span></div><p className="mt-3 text-xs font-semibold text-slate-600">Source mockée : {v[4]}</p>{ai && <p className="mt-3 rounded-2xl bg-white p-3 text-xs font-black text-cyan-950 ring-1 ring-cyan-100">Lecture IA : signal à relier à une note ou à une vérification humaine.</p>}<div className="mt-4 flex flex-wrap gap-2">{["Ajouter à la synthèse", "Créer action", "Vérifier", "Inclure note"].map((a) => <button key={a} onClick={() => on(a)} className="btn">{a}</button>)}</div></article>; }
function Suggest({ t, a, on }: { t: string; a: string[]; on: (x: string) => void }) { return <div className="rounded-2xl border border-cyan-100 bg-gradient-to-br from-white to-cyan-50 p-4"><p className="text-sm font-black">{t}</p><div className="mt-3 flex flex-wrap gap-2">{a.map((x) => <button key={x} onClick={() => on(x)} className={`${x === "Ignorer" ? "border border-cyan-200 bg-white text-cyan-950" : "bg-cyan-700 text-white"} rounded-full px-3 py-1.5 text-xs font-black`}>{x}</button>)}</div></div>; }
