apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mbambulaan-platform-secrets
  namespace: mbambulaan-production
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: mbambulaan-production-vault
  target:
    name: mbambulaan-platform-secrets-production
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: mbambulaan/production/platform
        property: database_url
    - secretKey: PUBLIC_BASE_URL
      remoteRef:
        key: mbambulaan/production/platform
        property: public_base_url
    - secretKey: OBJECT_STORAGE_ENDPOINT
      remoteRef:
        key: mbambulaan/production/platform
        property: object_storage_endpoint
    - secretKey: ENCRYPTION_KEY_ID
      remoteRef:
        key: mbambulaan/production/platform
        property: encryption_key_id
    - secretKey: TELEMETRY_ENDPOINT
      remoteRef:
        key: mbambulaan/production/platform
        property: telemetry_endpoint
    - secretKey: REDIS_URL
      remoteRef:
        key: mbambulaan/production/platform
        property: redis_url
