import Link from "next/link";
import { ArrowRight, BookOpen, MapPinned, ShieldCheck, Users } from "lucide-react";
import { PublicHeader } from "@/components/public/PublicHeader";
import { ProductProvider } from "@/components/providers/ProductProvider";
import { PublicAtlasWorkspace } from "@/components/ecosystem/PublicAtlasWorkspace";

export default function PublicAtlasPage() {
  return <main className="min-h-screen bg-[#f6f1e7]">
    <PublicHeader />
    <section className="public-atlas-hero px-5 py-14 text-white md:px-10 md:py-20"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-[#e9bf6c]"><MapPinned size={16}/> Atlas public du littoral</div><h1 className="mt-5 max-w-5xl font-serif text-5xl leading-[.98] tracking-[-.045em] md:text-7xl">Découvrir les quais.<br/><em>Comprendre la filière.</em></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#d6e6e5]">Une fenêtre ouverte sur les territoires, les produits et les capacités de la pêche artisanale. Ici, les informations sont publiques, agrégées et pédagogiques.</p><div className="mt-7 flex flex-wrap gap-3 text-xs font-bold"><span className="public-trust-pill"><ShieldCheck size={14}/> Données agrégées</span><span className="public-trust-pill"><Users size={14}/> Lecture accessible à tous</span></div></div></section>
    <ProductProvider><div className="mx-auto max-w-7xl px-5 py-10 md:px-10 md:py-14"><PublicAtlasWorkspace /><section className="mt-10 grid gap-px overflow-hidden rounded-[24px] border border-[#d8cdb8] bg-[#d8cdb8] md:grid-cols-2"><Link href="/community" className="group bg-[#fffaf0] p-6 transition hover:bg-white md:p-8"><Users className="text-[#0a6d68]"/><p className="public-kicker mt-5">Communautés</p><h2 className="mt-2 font-serif text-3xl text-[#10373a]">Rencontrer les métiers et les initiatives.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#60716f]">Portraits, savoir-faire, programmes collectifs et actualités des communautés du littoral.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#0a6d68]">Explorer la communauté <ArrowRight size={15}/></span></Link><Link href="/durabilite" className="group bg-[#f5efe2] p-6 transition hover:bg-[#fffaf0] md:p-8"><BookOpen className="text-[#a66f20]"/><p className="public-kicker mt-5">Pêche durable</p><h2 className="mt-2 font-serif text-3xl text-[#10373a]">Comprendre les pratiques qui préservent la valeur.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#60716f]">Provenance, saisonnalité, qualité et démarches de progrès expliquées simplement.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#8b601e]">Découvrir les engagements <ArrowRight size={15}/></span></Link></section></div></ProductProvider>
  </main>;
}
