import type { ISODateTime } from "./types";
import {
  UserExperienceCatalog,
  type ActorExperienceDefinition,
  type CrossActorExperienceFlow,
  type ExperienceMoment,
  type ExperienceFeature,
} from "./user-experience-catalog";

export interface MvpExperienceSeedResult {
  catalog: UserExperienceCatalog;
  summary: {
    actorExperienceCount: number;
    crossActorFlowCount: number;
    ministryValueMoments: number;
    atlasPremiumMoments: number;
  };
}

const moments = {
  fisher: [
    {
      id: "moment-fisher-onboarding",
      code: "fisher_onboarding",
      name: "Inscription assistée du pêcheur",
      kind: "onboarding",
      jobToBeDone: "Rejoindre Mbàmbulaan en quelques minutes avec son identité, sa pirogue et son site de rattachement.",
      trigger: "Le pêcheur accepte de participer au pilote.",
      expectedOutcome: "Profil opérationnel vérifié et prêt à déclarer une sortie ou un retour.",
      partnerActorKinds: ["cooperative", "landing_site"],
      ministryEvidence: ["nombre de pêcheurs enrôlés", "taux de profils vérifiés"],
      atlasPremiumValue: ["cartographie de la couverture des acteurs par territoire"],
      status: "ready",
    },
    {
      id: "moment-fisher-expected-return",
      code: "announce_expected_return",
      name: "Annonce du retour attendu",
      kind: "daily_operation",
      jobToBeDone: "Prévenir les acteurs du quai de l'heure estimée d'arrivée et des besoins à préparer.",
      trigger: "Le pêcheur estime son retour proche.",
      expectedOutcome: "Le site, la coopérative et les prestataires peuvent anticiper l'accueil.",
      partnerActorKinds: ["landing_site", "cooperative", "logistics"],
      ministryEvidence: ["retours attendus", "retards constatés", "capacité d'anticipation"],
      atlasPremiumValue: ["prévision des pics de débarquement", "détection de tensions de capacité"],
      status: "ready",
    },
    {
      id: "moment-fisher-landing",
      code: "confirm_landing",
      name: "Confirmation du débarquement",
      kind: "coordination",
      jobToBeDone: "Confirmer l'arrivée et rattacher la capture au bon voyage.",
      trigger: "La pirogue arrive au site de débarquement.",
      expectedOutcome: "Le débarquement devient traçable et partagé avec les acteurs autorisés.",
      partnerActorKinds: ["landing_site", "cooperative"],
      ministryEvidence: ["débarquements confirmés", "ponctualité", "origine des captures"],
      atlasPremiumValue: ["analyse des flux réels par site et période"],
      status: "ready",
    },
    {
      id: "moment-fisher-history",
      code: "review_activity_history",
      name: "Historique d'activité",
      kind: "decision",
      jobToBeDone: "Retrouver ses voyages, débarquements, lots et engagements.",
      trigger: "Le pêcheur veut vérifier ou justifier son activité.",
      expectedOutcome: "Une preuve simple et exploitable de son activité économique.",
      partnerActorKinds: ["cooperative", "financial_institution", "insurer"],
      ministryEvidence: ["activité consolidée par acteur"],
      atlasPremiumValue: ["profil d'activité et régularité opérationnelle"],
      status: "ready",
    },
  ],
  cooperative: [
    {
      id: "moment-cooperative-dashboard",
      code: "coordinate_members",
      name: "Coordination des membres",
      kind: "daily_operation",
      jobToBeDone: "Voir les sorties, retours attendus, débarquements, besoins et incidents des membres.",
      trigger: "Le responsable ouvre son espace de coordination.",
      expectedOutcome: "La coopérative agit avant les ruptures et accompagne ses membres.",
      partnerActorKinds: ["fisher", "landing_site", "logistics"],
      ministryEvidence: ["activité consolidée du GIE", "incidents ouverts", "besoins non couverts"],
      atlasPremiumValue: ["risques de saturation", "membres sous-accompagnés", "tendances d'activité"],
      status: "ready",
    },
    {
      id: "moment-cooperative-lot",
      code: "validate_lot_creation",
      name: "Validation et regroupement des lots",
      kind: "coordination",
      jobToBeDone: "Structurer les quantités débarquées en lots fiables et commercialisables.",
      trigger: "Les pesées sont enregistrées.",
      expectedOutcome: "Des lots avec origine, quantité, propriétaire et statut clairs.",
      partnerActorKinds: ["landing_site", "buyer", "processor"],
      ministryEvidence: ["volumes mis en lots", "traçabilité des lots"],
      atlasPremiumValue: ["analyse de concentration de l'offre", "prévision de disponibilité"],
      status: "ready",
    },
    {
      id: "moment-cooperative-incident",
      code: "manage_member_incident",
      name: "Gestion d'un incident membre",
      kind: "recovery",
      jobToBeDone: "Prendre en charge un blocage de service, de pesée, de lot ou d'engagement.",
      trigger: "Un membre ou un agent signale un problème.",
      expectedOutcome: "L'incident est assigné, suivi et clôturé avec une trace.",
      partnerActorKinds: ["fisher", "landing_site", "public_agency"],
      ministryEvidence: ["incidents", "délais de résolution", "causes récurrentes"],
      atlasPremiumValue: ["détection de causes racines et signaux faibles"],
      status: "ready",
    },
  ],
  landing_site: [
    {
      id: "moment-site-arrivals",
      code: "prepare_arrivals",
      name: "Préparation des arrivées",
      kind: "daily_operation",
      jobToBeDone: "Anticiper les retours, ressources, équipements et agents nécessaires.",
      trigger: "Des retours attendus sont annoncés.",
      expectedOutcome: "Le site sait quoi préparer et où se trouvent les tensions.",
      partnerActorKinds: ["fisher", "cooperative", "logistics"],
      ministryEvidence: ["charge prévisionnelle", "capacité déclarée", "tensions"],
      atlasPremiumValue: ["simulation de capacité et recommandations d'allocation"],
      status: "ready",
    },
    {
      id: "moment-site-weighing",
      code: "register_weighing",
      name: "Enregistrement de la pesée",
      kind: "daily_operation",
      jobToBeDone: "Enregistrer une pesée fiable, rattachée au débarquement et au propriétaire.",
      trigger: "La capture est prête à être pesée.",
      expectedOutcome: "Le volume réel devient une donnée de référence partagée.",
      partnerActorKinds: ["fisher", "cooperative"],
      ministryEvidence: ["volumes pesés", "écarts de poids", "complétude des données"],
      atlasPremiumValue: ["détection d'anomalies de poids et tendances par espèce"],
      status: "ready",
    },
    {
      id: "moment-site-service",
      code: "coordinate_service_need",
      name: "Coordination des services au quai",
      kind: "coordination",
      jobToBeDone: "Publier, affecter et suivre un besoin de glace, manutention, transport ou conservation.",
      trigger: "Un besoin est déclaré par un acteur.",
      expectedOutcome: "Le besoin est affecté et son exécution est confirmée.",
      partnerActorKinds: ["logistics", "cooperative", "fisher"],
      ministryEvidence: ["besoins créés", "taux de satisfaction", "délais d'exécution"],
      atlasPremiumValue: ["cartographie des déficits de service", "optimisation des capacités"],
      status: "ready",
    },
  ],
  buyer: [
    {
      id: "moment-buyer-discovery",
      code: "discover_available_lots",
      name: "Découverte des lots disponibles",
      kind: "daily_operation",
      jobToBeDone: "Identifier des lots fiables correspondant à ses besoins.",
      trigger: "L'acheteur consulte l'offre disponible.",
      expectedOutcome: "Il voit origine, quantité, qualité déclarée, disponibilité et vendeur.",
      partnerActorKinds: ["cooperative", "landing_site", "fisher"],
      ministryEvidence: ["lots consultés", "demande exprimée", "mise en relation"],
      atlasPremiumValue: ["prévision de tension offre-demande", "suggestion de sourcing"],
      status: "ready",
    },
    {
      id: "moment-buyer-commitment",
      code: "create_buyer_commitment",
      name: "Engagement sur un lot",
      kind: "coordination",
      jobToBeDone: "Réserver ou s'engager sur un lot avec quantité, prix ou conditions convenues.",
      trigger: "Un lot correspond à son besoin.",
      expectedOutcome: "L'engagement est partagé, horodaté et suivi jusqu'à exécution.",
      partnerActorKinds: ["cooperative", "fisher", "logistics"],
      ministryEvidence: ["engagements créés", "taux d'exécution", "volumes contractualisés"],
      atlasPremiumValue: ["analyse de fiabilité des engagements et dynamique de marché"],
      status: "ready",
    },
    {
      id: "moment-buyer-reception",
      code: "confirm_lot_reception",
      name: "Confirmation de réception",
      kind: "recovery",
      jobToBeDone: "Confirmer la réception ou signaler un écart de quantité, qualité ou délai.",
      trigger: "Le lot est livré ou collecté.",
      expectedOutcome: "La transaction est clôturée ou transformée en incident traçable.",
      partnerActorKinds: ["logistics", "cooperative", "processor"],
      ministryEvidence: ["réceptions confirmées", "litiges", "écarts"],
      atlasPremiumValue: ["analyse des ruptures de confiance et acteurs à risque"],
      status: "ready",
    },
  ],
  processor: [
    {
      id: "moment-processor-plan",
      code: "plan_processing_capacity",
      name: "Planification de transformation",
      kind: "decision",
      jobToBeDone: "Comparer ses besoins de matière première à l'offre à venir.",
      trigger: "Le transformateur prépare sa production.",
      expectedOutcome: "Il identifie les volumes à sécuriser et les écarts de capacité.",
      partnerActorKinds: ["buyer", "cooperative", "landing_site"],
      ministryEvidence: ["besoins de transformation", "capacité utilisée", "ruptures"],
      atlasPremiumValue: ["prévision d'approvisionnement et scénarios de production"],
      status: "ready",
    },
    {
      id: "moment-processor-trace",
      code: "trace_processed_input",
      name: "Traçabilité des intrants",
      kind: "daily_operation",
      jobToBeDone: "Rattacher les lots reçus à une opération de transformation.",
      trigger: "Un lot entre en transformation.",
      expectedOutcome: "L'origine et le devenir du lot restent consultables.",
      partnerActorKinds: ["buyer", "cooperative", "public_agency"],
      ministryEvidence: ["volumes transformés", "origine des intrants"],
      atlasPremiumValue: ["analyse des chaînes de valeur et pertes de matière"],
      status: "ready",
    },
  ],
  logistics: [
    {
      id: "moment-logistics-capacity",
      code: "declare_service_capacity",
      name: "Déclaration de capacité",
      kind: "daily_operation",
      jobToBeDone: "Déclarer ses capacités disponibles de transport, glace, manutention ou conservation.",
      trigger: "Le prestataire met à jour sa disponibilité.",
      expectedOutcome: "La plateforme peut proposer une allocation pertinente.",
      partnerActorKinds: ["landing_site", "cooperative", "buyer"],
      ministryEvidence: ["capacités disponibles", "zones non couvertes"],
      atlasPremiumValue: ["prévision de déficit de service", "optimisation territoriale"],
      status: "ready",
    },
    {
      id: "moment-logistics-execution",
      code: "confirm_service_execution",
      name: "Confirmation d'exécution",
      kind: "coordination",
      jobToBeDone: "Accepter une allocation puis confirmer le service réalisé.",
      trigger: "Un besoin compatible lui est affecté.",
      expectedOutcome: "Le demandeur et le coordinateur disposent d'une preuve d'exécution.",
      partnerActorKinds: ["landing_site", "fisher", "buyer"],
      ministryEvidence: ["services affectés", "services réalisés", "délais"],
      atlasPremiumValue: ["performance des prestataires et capacité fiable"],
      status: "ready",
    },
  ],
  ministry: [
    {
      id: "moment-ministry-command",
      code: "monitor_pilot_operations",
      name: "Vue de pilotage opérationnel",
      kind: "decision",
      jobToBeDone: "Comprendre en temps utile ce qui se passe dans le territoire pilote.",
      trigger: "Le responsable institutionnel consulte Mbàmbulaan Government.",
      expectedOutcome: "Il voit acteurs actifs, retours, volumes, incidents, capacités et engagements.",
      partnerActorKinds: ["public_agency", "cooperative", "landing_site"],
      ministryEvidence: ["indicateurs consolidés", "qualité des données", "couverture territoriale"],
      atlasPremiumValue: ["alertes prioritaires", "explications causales", "scénarios d'intervention"],
      status: "ready",
    },
    {
      id: "moment-ministry-briefing",
      code: "generate_ministry_briefing",
      name: "Briefing décisionnel",
      kind: "decision",
      jobToBeDone: "Obtenir une synthèse courte des faits, risques, causes et actions possibles.",
      trigger: "Une revue du pilote ou une tension importante survient.",
      expectedOutcome: "Une décision peut être préparée avec des preuves opérationnelles.",
      partnerActorKinds: ["public_agency", "development_partner"],
      ministryEvidence: ["briefings générés", "actions décidées", "résultats suivis"],
      atlasPremiumValue: ["briefing Atlas Premium avec scénarios comparés"],
      status: "ready",
    },
  ],
  public_agency: [
    {
      id: "moment-agency-field",
      code: "supervise_field_operations",
      name: "Supervision de terrain",
      kind: "daily_operation",
      jobToBeDone: "Suivre les activités et vérifier les incidents, données ou opérations nécessitant une intervention.",
      trigger: "L'agence ouvre son portefeuille de sites.",
      expectedOutcome: "Les priorités de terrain sont visibles et assignables.",
      partnerActorKinds: ["ministry", "landing_site", "cooperative"],
      ministryEvidence: ["contrôles", "anomalies", "résolutions"],
      atlasPremiumValue: ["priorisation des contrôles et explication des anomalies"],
      status: "ready",
    },
  ],
  development_partner: [
    {
      id: "moment-partner-program",
      code: "monitor_program_results",
      name: "Suivi d'un programme d'appui",
      kind: "decision",
      jobToBeDone: "Relier les engagements d'un programme à des bénéficiaires et résultats observables.",
      trigger: "Le partenaire consulte un programme financé ou soutenu.",
      expectedOutcome: "Il voit bénéficiaires, engagements, exécution et résultats.",
      partnerActorKinds: ["ministry", "public_agency", "cooperative"],
      ministryEvidence: ["programmes", "bénéficiaires", "résultats"],
      atlasPremiumValue: ["analyse d'impact, attribution et scénarios de ciblage"],
      status: "ready",
    },
  ],
  financial_institution: [
    {
      id: "moment-finance-assess",
      code: "assess_financing_case",
      name: "Évaluation d'un dossier de financement",
      kind: "decision",
      jobToBeDone: "Étudier un acteur ou une organisation avec des preuves d'activité et de régularité.",
      trigger: "Une demande de financement est soumise.",
      expectedOutcome: "Le dossier contient activité, engagements, incidents et historique vérifiable.",
      partnerActorKinds: ["fisher", "cooperative", "ministry"],
      ministryEvidence: ["dossiers étudiés", "acteurs financés"],
      atlasPremiumValue: ["score explicable de régularité et simulation de risque"],
      status: "ready",
    },
  ],
  insurer: [
    {
      id: "moment-insurer-risk",
      code: "assess_insurance_risk",
      name: "Évaluation du risque assuré",
      kind: "decision",
      jobToBeDone: "Analyser l'exposition et les événements opérationnels d'un acteur ou d'une flotte.",
      trigger: "Un contrat ou sinistre est étudié.",
      expectedOutcome: "L'assureur accède à des preuves autorisées et traçables.",
      partnerActorKinds: ["fisher", "cooperative", "public_agency"],
      ministryEvidence: ["acteurs assurables", "incidents déclarés"],
      atlasPremiumValue: ["profil de risque dynamique et détection de concentration"],
      status: "ready",
    },
  ],
} satisfies Record<string, ExperienceMoment[]>;

const features: ExperienceFeature[] = [
  {
    id: "feature-assisted-onboarding",
    code: "assisted_onboarding",
    name: "Onboarding assisté multi-acteurs",
    capabilityCodes: ["identity", "trust", "affiliation", "role_assignment"],
    actorKinds: ["fisher", "cooperative", "landing_site", "buyer", "processor", "logistics"],
    maturity: "mvp",
    status: "ready",
  },
  {
    id: "feature-operational-coordination",
    code: "operational_coordination",
    name: "Coordination opérationnelle de bout en bout",
    capabilityCodes: [
      "expected_return",
      "landing",
      "weighing",
      "lot_creation",
      "service_need",
      "capacity_allocation",
      "commitment",
    ],
    actorKinds: ["fisher", "cooperative", "landing_site", "buyer", "processor", "logistics"],
    maturity: "mvp",
    status: "ready",
  },
  {
    id: "feature-government-visibility",
    code: "government_visibility",
    name: "Visibilité institutionnelle opérationnelle",
    capabilityCodes: ["operational_metrics", "tension_reporting", "audit", "territory_visibility"],
    actorKinds: ["ministry", "public_agency", "development_partner"],
    maturity: "mvp",
    status: "ready",
  },
  {
    id: "feature-atlas-premium",
    code: "atlas_premium_decision_intelligence",
    name: "Atlas Premium Decision Intelligence",
    capabilityCodes: ["causal_analysis", "scenario_evaluation", "briefing", "risk_detection"],
    actorKinds: ["ministry", "public_agency", "development_partner", "financial_institution", "insurer"],
    maturity: "mvp",
    status: "ready",
  },
];

const actorExperiences: ActorExperienceDefinition[] = [
  {
    id: "experience-fisher-mvp",
    actorKind: "fisher",
    productCodes: ["fisher"],
    promise: "Mieux préparer son retour, sécuriser ses opérations et disposer d'une preuve fiable de son activité.",
    momentIds: moments.fisher.map((item) => item.id),
    featureIds: ["feature-assisted-onboarding", "feature-operational-coordination"],
    measurableBenefits: ["moins d'attente", "meilleure coordination", "historique d'activité", "accès facilité à des partenaires"],
    ministryValue: ["visibilité sur les acteurs et les flux réels"],
    atlasPremiumValue: ["prévisions et profil d'activité explicable"],
    status: "ready",
  },
  {
    id: "experience-cooperative-mvp",
    actorKind: "cooperative",
    productCodes: ["cooperative"],
    promise: "Coordonner les membres, structurer les lots et traiter les incidents avec une information partagée.",
    momentIds: moments.cooperative.map((item) => item.id),
    featureIds: ["feature-assisted-onboarding", "feature-operational-coordination"],
    measurableBenefits: ["activité consolidée", "lots mieux structurés", "incidents suivis", "services mieux affectés"],
    ministryValue: ["vue consolidée des organisations locales"],
    atlasPremiumValue: ["risques et tendances de performance organisationnelle"],
    status: "ready",
  },
  {
    id: "experience-landing-site-mvp",
    actorKind: "landing_site",
    productCodes: ["cooperative", "government"],
    promise: "Préparer les arrivées, fiabiliser les pesées et coordonner les services du site.",
    momentIds: moments.landing_site.map((item) => item.id),
    featureIds: ["feature-assisted-onboarding", "feature-operational-coordination", "feature-government-visibility"],
    measurableBenefits: ["meilleure anticipation", "données fiables", "réduction des blocages", "capacité visible"],
    ministryValue: ["lecture opérationnelle du site et de ses tensions"],
    atlasPremiumValue: ["simulation de capacité et détection d'anomalies"],
    status: "ready",
  },
  {
    id: "experience-buyer-mvp",
    actorKind: "buyer",
    productCodes: ["business"],
    promise: "Trouver des lots fiables, formaliser un engagement et suivre la réception.",
    momentIds: moments.buyer.map((item) => item.id),
    featureIds: ["feature-assisted-onboarding", "feature-operational-coordination"],
    measurableBenefits: ["sourcing plus rapide", "engagements traçables", "moins de litiges", "visibilité sur l'offre"],
    ministryValue: ["lecture de la demande et des transactions réelles"],
    atlasPremiumValue: ["prévision offre-demande et fiabilité des partenaires"],
    status: "ready",
  },
  {
    id: "experience-processor-mvp",
    actorKind: "processor",
    productCodes: ["business"],
    promise: "Sécuriser l'approvisionnement et tracer les intrants jusqu'à la transformation.",
    momentIds: moments.processor.map((item) => item.id),
    featureIds: ["feature-operational-coordination"],
    measurableBenefits: ["meilleure planification", "approvisionnement plus fiable", "traçabilité des intrants"],
    ministryValue: ["visibilité sur la transformation et les débouchés"],
    atlasPremiumValue: ["scénarios d'approvisionnement et analyse des pertes"],
    status: "ready",
  },
  {
    id: "experience-logistics-mvp",
    actorKind: "logistics",
    productCodes: ["business"],
    promise: "Valoriser sa capacité disponible et recevoir des allocations de service qualifiées.",
    momentIds: moments.logistics.map((item) => item.id),
    featureIds: ["feature-operational-coordination"],
    measurableBenefits: ["capacité mieux utilisée", "demandes plus qualifiées", "preuves d'exécution"],
    ministryValue: ["cartographie des capacités et déficits de service"],
    atlasPremiumValue: ["optimisation territoriale des services"],
    status: "ready",
  },
  {
    id: "experience-ministry-mvp",
    actorKind: "ministry",
    productCodes: ["government", "atlas"],
    promise: "Piloter le territoire avec des données opérationnelles fiables et des analyses décisionnelles premium.",
    momentIds: moments.ministry.map((item) => item.id),
    featureIds: ["feature-government-visibility", "feature-atlas-premium"],
    measurableBenefits: ["visibilité terrain", "alertes prioritaires", "briefings décisionnels", "suivi des résultats"],
    ministryValue: ["pilotage fondé sur les opérations réelles"],
    atlasPremiumValue: ["causalité, scénarios, recommandations et briefings"],
    status: "ready",
  },
  {
    id: "experience-agency-mvp",
    actorKind: "public_agency",
    productCodes: ["government", "atlas"],
    promise: "Superviser les sites, prioriser les interventions et rendre compte au ministère.",
    momentIds: moments.public_agency.map((item) => item.id),
    featureIds: ["feature-government-visibility", "feature-atlas-premium"],
    measurableBenefits: ["interventions mieux ciblées", "anomalies suivies", "reporting simplifié"],
    ministryValue: ["chaîne de supervision entre terrain et décision"],
    atlasPremiumValue: ["priorisation intelligente des contrôles"],
    status: "ready",
  },
  {
    id: "experience-development-mvp",
    actorKind: "development_partner",
    productCodes: ["development", "atlas"],
    promise: "Relier financements, bénéficiaires, engagements et résultats observables.",
    momentIds: moments.development_partner.map((item) => item.id),
    featureIds: ["feature-government-visibility", "feature-atlas-premium"],
    measurableBenefits: ["suivi d'exécution", "preuves de résultats", "meilleur ciblage"],
    ministryValue: ["alignement programmes-public terrain"],
    atlasPremiumValue: ["analyse d'impact et scénarios de ciblage"],
    status: "ready",
  },
  {
    id: "experience-finance-mvp",
    actorKind: "financial_institution",
    productCodes: ["finance", "atlas"],
    promise: "Étudier des dossiers avec des preuves d'activité plutôt qu'avec des déclarations isolées.",
    momentIds: moments.financial_institution.map((item) => item.id),
    featureIds: ["feature-atlas-premium"],
    measurableBenefits: ["dossiers mieux qualifiés", "risque mieux compris", "décision plus rapide"],
    ministryValue: ["meilleure inclusion financière des acteurs structurés"],
    atlasPremiumValue: ["score explicable et simulation de risque"],
    status: "ready",
  },
  {
    id: "experience-insurer-mvp",
    actorKind: "insurer",
    productCodes: ["finance", "atlas"],
    promise: "Comprendre le risque réel et instruire contrat ou sinistre avec des preuves autorisées.",
    momentIds: moments.insurer.map((item) => item.id),
    featureIds: ["feature-atlas-premium"],
    measurableBenefits: ["meilleure segmentation", "preuves plus fiables", "gestion du risque améliorée"],
    ministryValue: ["élargissement de l'assurabilité"],
    atlasPremiumValue: ["profil de risque dynamique"],
    status: "ready",
  },
];

const crossActorFlows: CrossActorExperienceFlow[] = [
  {
    id: "flow-sea-to-lot",
    code: "sea_to_lot",
    name: "De la mer au lot traçable",
    actorKinds: ["fisher", "landing_site", "cooperative"],
    momentCodes: ["announce_expected_return", "confirm_landing", "register_weighing", "validate_lot_creation"],
    sharedOutcome: "Un lot fiable, relié au voyage, au débarquement, à la pesée et au propriétaire.",
    governmentOutputs: ["volumes débarqués", "origine", "délais", "qualité de données"],
    atlasPremiumOutputs: ["prévision de flux", "anomalies", "causes de retard"],
    status: "ready",
  },
  {
    id: "flow-lot-to-reception",
    code: "lot_to_reception",
    name: "Du lot à l'engagement exécuté",
    actorKinds: ["cooperative", "buyer", "logistics", "processor"],
    momentCodes: ["discover_available_lots", "create_buyer_commitment", "confirm_service_execution", "confirm_lot_reception", "trace_processed_input"],
    sharedOutcome: "Une transaction coordonnée et traçable jusqu'à la réception ou transformation.",
    governmentOutputs: ["volumes engagés", "volumes reçus", "écarts et litiges"],
    atlasPremiumOutputs: ["fiabilité des engagements", "tension offre-demande", "risques de rupture"],
    status: "ready",
  },
  {
    id: "flow-service-need",
    code: "service_need_to_execution",
    name: "Du besoin de service à l'exécution",
    actorKinds: ["fisher", "landing_site", "cooperative", "logistics"],
    momentCodes: ["coordinate_service_need", "declare_service_capacity", "confirm_service_execution"],
    sharedOutcome: "Un besoin réel reçoit une capacité adaptée et une preuve d'exécution.",
    governmentOutputs: ["taux de couverture", "délais", "zones déficitaires"],
    atlasPremiumOutputs: ["allocation recommandée", "prévision de saturation", "capacité fiable"],
    status: "ready",
  },
  {
    id: "flow-incident-resolution",
    code: "incident_to_resolution",
    name: "De l'incident à la résolution institutionnelle",
    actorKinds: ["fisher", "cooperative", "landing_site", "public_agency", "ministry"],
    momentCodes: ["manage_member_incident", "supervise_field_operations", "monitor_pilot_operations", "generate_ministry_briefing"],
    sharedOutcome: "Un incident est signalé, assigné, résolu et transformé en apprentissage institutionnel.",
    governmentOutputs: ["incidents", "délais de résolution", "actions prises"],
    atlasPremiumOutputs: ["cause racine", "signaux faibles", "scénarios de prévention"],
    status: "ready",
  },
  {
    id: "flow-program-impact",
    code: "program_to_impact",
    name: "Du programme aux résultats observables",
    actorKinds: ["development_partner", "ministry", "public_agency", "cooperative", "fisher"],
    momentCodes: ["monitor_program_results", "monitor_pilot_operations", "coordinate_members", "review_activity_history"],
    sharedOutcome: "Les ressources mobilisées sont reliées à des bénéficiaires et résultats vérifiables.",
    governmentOutputs: ["bénéficiaires", "engagements", "résultats"],
    atlasPremiumOutputs: ["analyse d'impact", "attribution", "ciblage recommandé"],
    status: "ready",
  },
  {
    id: "flow-evidence-to-finance",
    code: "activity_evidence_to_finance",
    name: "De la preuve d'activité à l'accès financier",
    actorKinds: ["fisher", "cooperative", "financial_institution", "insurer"],
    momentCodes: ["review_activity_history", "assess_financing_case", "assess_insurance_risk"],
    sharedOutcome: "Un acteur peut présenter une activité vérifiable à un financeur ou assureur.",
    governmentOutputs: ["acteurs accompagnés", "dossiers étudiés", "inclusion financière"],
    atlasPremiumOutputs: ["score explicable", "simulation de risque", "profil dynamique"],
    status: "ready",
  },
];

export function seedMvpUserExperienceCatalog(createdAt: ISODateTime): MvpExperienceSeedResult {
  const catalog = new UserExperienceCatalog();

  for (const feature of features) catalog.registerFeature(feature);
  for (const group of Object.values(moments)) {
    for (const moment of group) catalog.registerMoment(moment);
  }
  for (const experience of actorExperiences) catalog.registerActorExperience(experience);
  for (const flow of crossActorFlows) catalog.registerCrossActorFlow(flow);

  const snapshot = catalog.snapshot();
  const allMoments = snapshot.moments;

  return {
    catalog,
    summary: {
      actorExperienceCount: snapshot.actorExperiences.length,
      crossActorFlowCount: snapshot.crossActorFlows.length,
      ministryValueMoments: allMoments.filter((item) => item.ministryEvidence.length > 0).length,
      atlasPremiumMoments: allMoments.filter((item) => item.atlasPremiumValue.length > 0).length,
    },
  };
}
