import Link from "next/link";

type Role = "etat" | "ong" | "collectivite" | "pecheur" | "mareyeur" | "exportateur" | "organisation" | "investisseur";
type Metric = [string, string, string];

type Space = {
  role: Role;
  label: string;
  context: string;
  headline: string;
  subhead: string;
  cta: string;
  metrics: Metric[];
  sections: string[];
};

const aliases: Record<string, Role> = { entreprise: "exportateur", "acteur-terrain": "pecheur" };
const spaces: Record<Role, Space> = {
  etat: { role: "etat", label: "Espace Ministère", context: "Joal / Petite-Côte", headline: "Décider avec une vue filière consolidée.", subhead: "Tensions, financements, programmes et note de décision dans un espace institutionnel.", cta: "Pilote institutionnel", metrics: [["Territoires", "03", "Joal prioritaire"], ["Signaux", "12", "4 à arbitrer"], ["Financements", "08", "27 M FCFA"], ["Programmes", "05", "2 doublons"]], sections: ["carte", "note", "financement"] },
  ong: { role: "ong", label: "Espace Programme", context: "Programme résilience", headline: "Piloter l’action, prouver sans surpromettre.", subhead: "Bénéficiaires, preuves, alertes et reporting bailleur.", cta: "Démo programme", metrics: [["Bénéficiaires", "38", "suivis"], ["Preuves", "06", "collectées"], ["Actions", "11", "terrain"], ["Alertes", "03", "ouvertes"]], sections: ["pipeline", "beneficiaires", "impact"] },
  collectivite: { role: "collectivite", label: "Espace Collectivité", context: "Commune de Joal-Fadiouth", headline: "Transformer les problèmes du quai en actions locales.", subhead: "Une vue simple pour mobiliser, financer et rendre compte.", cta: "Territoire pilote", metrics: [["Quais", "02", "suivis"], ["Acteurs", "57", "locaux"], ["Actions", "03", "ouvertes"], ["Partenaires", "05", "mobilisables"]], sections: ["commune", "actions", "partenaires"] },
  pecheur: { role: "pecheur", label: "Parcours Pêcheur", context: "Relais quai", headline: "Un signal simple. Un retour clair.", subhead: "Pas de tableau de bord lourd : relais, appel, message et statut lisible.", cta: "Activer relais", metrics: [["Signaux", "04", "semaine"], ["Demandes", "03", "suivies"], ["Relais", "01", "Joal"], ["Confiance", "78", "score"]], sections: ["mobile", "timeline", "services"] },
  mareyeur: { role: "mareyeur", label: "Espace Mareyeur", context: "Flux Joal vers Dakar", headline: "Anticiper les flux, sécuriser la qualité.", subhead: "Produits, besoins marché, logistique, prix indicatifs et fonds de roulement.", cta: "Organiser flux", metrics: [["Lots", "03", "disponibles"], ["Besoins", "05", "marché"], ["Qualité", "Moyen", "à suivre"], ["Prix", "820", "FCFA/kg"]], sections: ["produits", "prix", "logistique"] },
  exportateur: { role: "exportateur", label: "Espace Exportateur", context: "Qualification commerciale", headline: "Réduire l’incertitude avant d’acheter.", subhead: "Qualité, trace, risques, conditions et coordination sans marketplace.", cta: "Qualifier opportunité", metrics: [["Opportunités", "04", "qualifiées"], ["Lots", "09", "suivis"], ["Trace", "71%", "partielle"], ["Risques", "02", "ouverts"]], sections: ["pipeline", "risque", "lots"] },
  organisation: { role: "organisation", label: "Espace Organisation", context: "GIE et réseau local", headline: "Transformer les demandes dispersées en dossier collectif.", subhead: "Registre membres, besoins agrégés, plaidoyer, preuves et partenaires.", cta: "Structurer pilote", metrics: [["Membres", "24", "recensés"], ["Demandes", "07", "collectives"], ["Partenaires", "03", "cibles"], ["Preuves", "05", "disponibles"]], sections: ["registre", "plaidoyer", "partenaires"] },
  investisseur: { role: "investisseur", label: "Espace Investisseur", context: "Thèse infrastructure", headline: "Une infrastructure verticale, pas une app de niche.", subhead: "Segments payeurs, flux de valeur, risques, pilotes et trajectoire économique.", cta: "Session investisseur", metrics: [["Payeurs", "08", "segments"], ["Flux", "03", "valeur"], ["Pilotes", "02", "territoires"], ["Risques", "05", "suivis"]], sections: ["ecosysteme", "payeurs", "roadmap"] }
};

export function RoleWorkspace({ slug }: { slug: string }) {
  const role = (aliases[slug] ?? slug) as Role;
  const space = spaces[role] ?? spaces.etat;
  return <main className="min-h-screen bg-[#f6f3ea] text-[#112f36]"><Header label={space.label} cta={space.cta} /><section className="mx-auto max-w-7xl px-5 pb-16 sm:px-8"><Hero space={space} />{role === "etat" && <Ministry />}{role === "ong" && <Program />}{role === "collectivite" && <Collectivity />}{role === "pecheur" && <Fisher />}{role === "mareyeur" && <Mareyeur />}{role === "exportateur" && <Exporter />}{role === "organisation" && <Organization />}{role === "investisseur" && <Investor />}</section></main>;
}

function Header({ label, cta }: { label: string; cta: string }) { return <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-3 font-black"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#102f3a] text-white">Mb</span><span>{label}</span></Link><nav className="hidden items-center gap-5 text-sm font-black text-[#50636a] md:flex"><Link href="/demo">Changer de rôle</Link><Link href="/devis" className="rounded-full bg-[#102f3a] px-4 py-2 text-white">{cta}</Link></nav></header>; }
function Hero({ space }: { space: Space }) { return <div className="grid gap-6 py-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#0d6f8d]">{space.context}</p><h1 className="mt-4 text-4xl font-black leading-none tracking-[-0.05em] text-[#102f3a] sm:text-6xl">{space.headline}</h1><p className="mt-4 max-w-xl text-base font-bold leading-7 text-[#50636a]">{space.subhead}</p><div className="mt-6 flex flex-wrap gap-3"><Action href="/devis" primary>{space.cta}</Action><Action href="/demande-demo">Démo complète</Action></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{space.metrics.map((m)=><MetricCard key={m[0]} metric={m}/>)}</div></div>; }
function MetricCard({ metric }: { metric: Metric }) { return <article className="rounded-2xl border border-[#dbe7e8] bg-white p-4 shadow-sm"><p className="text-[0.65rem] font-black uppercase tracking-[0.14em] text-[#72838a]">{metric[0]}</p><p className="mt-2 text-3xl font-black tracking-[-0.04em] text-[#102f3a]">{metric[1]}</p><p className="mt-1 text-xs font-bold text-[#697b82]">{metric[2]}</p></article>; }
function Action({ href, children, primary = false }: { href: string; children: React.ReactNode; primary?: boolean }) { return <Link href={href} className={`inline-flex min-h-11 items-center justify-center rounded-full px-5 text-sm font-black ${primary ? "bg-[#0d6f8d] text-white" : "border border-[#d5e1e3] bg-white text-[#102f3a]"}`}>{children}</Link>; }
function Panel({ title, children, dark = false }: { title: string; children: React.ReactNode; dark?: boolean }) { return <article className={`rounded-[1.8rem] p-5 shadow-xl ${dark ? "bg-[#102f3a] text-white" : "border border-[#dbe7e8] bg-white text-[#102f3a]"}`}><h2 className="text-xl font-black tracking-[-0.03em]">{title}</h2>{children}</article>; }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="mt-4 overflow-hidden rounded-2xl border border-[#dbe7e8]"><div className="grid bg-[#eef5f5] text-[0.65rem] font-black uppercase tracking-[0.12em] text-[#6b7c83]" style={{ gridTemplateColumns: `repeat(${headers.length}, minmax(0, 1fr))` }}>{headers.map((h)=><span key={h} className="p-3">{h}</span>)}</div>{rows.map((row)=><div key={row.join("-")} className="grid border-t border-[#dbe7e8] bg-white text-sm font-bold text-[#30444b]" style={{ gridTemplateColumns: `repeat(${headers.length}, minmax(0, 1fr))` }}>{row.map((cell)=><span key={cell} className="p-3">{cell}</span>)}</div>)}</div>; }
function MapView({ labels }: { labels: string[] }) { return <div className="relative mt-4 min-h-[18rem] overflow-hidden rounded-[1.6rem] bg-[#dfecea]"><div className="absolute inset-6 rounded-[45%] border border-[#91aaa7]" /><div className="absolute left-1/2 top-8 h-[15rem] w-px bg-[#91aaa7]" /><div className="absolute left-8 right-8 top-1/2 h-px bg-[#91aaa7]" />{labels.map((label,i)=><div key={label} className="absolute -translate-x-1/2 -translate-y-1/2" style={{ left: `${25 + i*18}%`, top: `${35 + (i%2)*28}%` }}><span className="mx-auto block h-4 w-4 rounded-full border-2 border-white bg-[#0d6f8d] shadow-lg" /><span className="mt-2 block rounded-full bg-white px-2 py-1 text-[0.65rem] font-black text-[#102f3a] shadow-sm">{label}</span></div>)}</div>; }
function Bars({ rows }: { rows: string[][] }) { return <div className="mt-4 grid gap-3">{rows.map(([label,value,note])=><div key={label}><div className="flex justify-between text-sm font-black"><span>{label}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-[#dbe7e8]"><div className="h-2 rounded-full bg-[#0d6f8d]" style={{ width: `${value}%` }} /></div><p className="mt-1 text-xs font-bold text-[#6b7c83]">{note}</p></div>)}</div>; }
function Steps({ rows }: { rows: string[][] }) { return <div className="mt-4 grid gap-3">{rows.map(([title,status],i)=><div key={title} className="flex gap-3 rounded-2xl bg-white p-4 shadow-sm"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#102f3a] text-xs font-black text-white">{i+1}</span><div><p className="font-black text-[#102f3a]">{title}</p><span className="mt-2 inline-flex rounded-full bg-[#eef5f5] px-3 py-1 text-xs font-black uppercase tracking-[0.12em] text-[#0d6f8d]">{status}</span></div></div>)}</div>; }

function Ministry() { return <><div className="grid gap-5 lg:grid-cols-[1.05fr_0.95fr]"><Panel title="Carte des tensions"><MapView labels={["Joal", "Mbour", "Kayar", "Dakar"]} /></Panel><Panel title="Décision recommandée" dark><p className="mt-4 text-2xl font-black">Prioriser un pilote froid à Joal</p><p className="mt-3 text-sm font-semibold leading-6 text-white/70">Coordonner commune, mareyeurs, ONG et service pêche.</p><Steps rows={[["Signal conservation confirmé","prêt"],["Programme partenaire identifié","en cours"],["Note ministère préparée","prêt"]]} /></Panel></div><Panel title="Demandes de financement"><Table headers={["Besoin","Porteur","Budget","Statut"]} rows={[["Unité glace","Commune / GIE","18 M","Prioritaire"],["Caisses isothermes","Mareyeurs","6 M","Groupable"],["Formation qualité","ONG","3 M","Actif"]]} /></Panel></>; }
function Program() { return <div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><Panel title="Pipeline programme"><Steps rows={[["Diagnostic territoire","prêt"],["Sensibilisation qualité","en cours"],["Financement froid","à lancer"],["Preuve terrain","à faire"],["Reporting bailleur","prêt"]]} /></Panel><Panel title="Bénéficiaires"><Table headers={["Groupe","Zone","Besoin","Preuve"]} rows={[["GIE femmes","Joal","froid","validée"],["Relais quai","Mbour","formation","partielle"],["Mareyeurs","Joal","fonds","déclarative"]]} /><Bars rows={[["Couverture","72","Joal couvert"],["Preuve","68","partielle"],["Risque doublon","54","à coordonner"]]} /></Panel></div>; }
function Collectivity() { return <div className="grid gap-5 lg:grid-cols-2"><Panel title="Carte communale"><MapView labels={["Quai","Marché","Transfo","Mairie"]} /></Panel><Panel title="Action communale"><Steps rows={[["Besoin froid confirmé","prêt"],["Partenaire identifié","en cours"],["Note maire prête","prêt"],["Financement à cadrer","à lancer"]]} /></Panel></div>; }
function Fisher() { return <div className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]"><Panel title="Actions simples"><div className="mt-4 grid gap-3"><Action href="/demande-demo" primary>Signaler disponibilité</Action><Action href="/devis">Demander financement</Action><Action href="/demo">Contacter relais</Action></div></Panel><Panel title="Suivi de demande"><Steps rows={[["Disponibilité envoyée par appel","reçu"],["Relais confirme le besoin glace","en cours"],["Mareyeur intéressé","disponible"],["Retour attendu","à faire"]]} /></Panel></div>; }
function Mareyeur() { return <div className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><Panel title="Portefeuille produits"><Table headers={["Espèce","Volume","Qualité","Délai","Action"]} rows={[["Sardinelle","1,2 t","sensible","4h","organiser"],["Dorade","460 kg","frais","8h","surveiller"],["Thiof","180 kg","premium","12h","prix"]]} /></Panel><Panel title="Prix indicatif"><Bars rows={[["Sardinelle","82","demande forte"],["Dorade","66","marché stable"],["Thiof","91","premium"]]} /></Panel></div>; }
function Exporter() { return <div className="grid gap-5 lg:grid-cols-2"><Panel title="Pipeline opportunités"><Steps rows={[["Lot Joal repéré","prêt"],["Qualité évaluée","en cours"],["Preuve demandée","à faire"],["Coordination achat","à lancer"]]} /></Panel><Panel title="Matrice risques"><Bars rows={[["Qualité","87","délai froid surveillé"],["Trace","71","preuve partielle"],["Disponibilité","78","volume à confirmer"],["Logistique","63","transport ouvert"]]} /></Panel></div>; }
function Organization() { return <div className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><Panel title="Registre membres"><Table headers={["Groupe","Zone","Besoin","Statut"]} rows={[["GIE femmes","Joal","froid","prioritaire"],["Pêcheurs réf.","Kayar","moteur","à valider"],["Mareyeurs","Mbour","fonds","groupable"]]} /></Panel><Panel title="Note de plaidoyer" dark><p className="mt-4 text-sm font-semibold leading-6 text-white/72">Équipement froid mutualisé pour 3 quais. Besoins récurrents, pertes de valeur, acteurs recensés. Registre à consolider.</p></Panel></div>; }
function Investor() { return <div className="grid gap-5 lg:grid-cols-2"><Panel title="Carte écosystème"><MapView labels={["État", "ONG", "Commune", "Entreprise", "Terrain"]} /></Panel><Panel title="Matrice payeurs"><Table headers={["Segment","Pourquoi","Modèle"]} rows={[["État","pilotage","licence"],["ONG","reporting","forfait"],["Entreprise","incertitude","abonnement"]]} /></Panel></div>; }
